// 技の問題データを2階層で管理する
// 1. problemBank: 技の問題そのもの（章ごとに1回だけ定義。番号・レベル・Check Point文）
// 2. terms: 学期ごとの講の割り当て（問題バンクを参照し、講ごとに宿題必須番号をクラス別に持つ）
//    homeworkNumbersSSSA = SS/SAクラスの宿題必須番号、homeworkNumbersSBCT = SBC/Tクラスの宿題必須番号
//    referenceNumbers = 本来の対象範囲外だが行き場がないため参考として表示する問題番号

const problemBank = {
  "1a-2": {
    title: "技1A 第2章（最大・最小）",
    problems: [
      { number: 1, level: 1, checkPoint: "平行移動、対称移動の公式は？" },
      { number: 2, level: 1, checkPoint: "絶対値入り関数のグラフの書き方は？(特に、y=|f(x)|の形だと？)" },
      { number: 3, level: 2, checkPoint: "場合分けが必要な式・グラフの特徴は？" },
      { number: 4, level: 2, checkPoint: "式処理のポイント３つは？Maxminで文字を置換したときの注意点は？" },
      { number: 5, level: 2, checkPoint: "1変数関数で場合分けが必要なMaxminは、グラフを描いた後、何に注意して場合分けする？" },
      { number: 6, level: 3, checkPoint: "グラフに文字定数を含む場合の場合分けはどう考える？" },
      { number: 7, level: 2, checkPoint: "１変数関数の最大最小の求め方３つは？" },
      { number: 8, level: 3, checkPoint: "=kとおく解法は、結局どのような条件を考えているか説明できる？" },
      { number: 9, level: 2, checkPoint: "簡単な等式条件がある２変数関数のMaxminの求め方と注意点は？" },
      { number: 10, level: 2, checkPoint: "２変数関数で、=kとおいてMaxmin求めるのはどんな時？" },
      { number: 11, level: 2, checkPoint: "対称式の扱いのポイントと、注意点は？" },
      { number: 12, level: 3, checkPoint: "三角置換はどのような時に考慮する？" },
      { number: 13, level: 2, checkPoint: "予選決勝法の使える場面と、その方法は？" },
      { number: 14, level: 3, checkPoint: "予選決勝法で固定する文字は、何を心がけて選択する？" },
      { number: 15, level: 2, checkPoint: "２変数関数のMaxminで用いる有名不等式とは？" },
      { number: 16, level: 4, checkPoint: "２変数関数のMaxminで有名不等式が使えるパターンってどんなの？" },
      { number: 17, level: 2, checkPoint: "３変数関数のMaxminの解法でまず考えるべきこととは？" },
      { number: 18, level: 3, checkPoint: "３変数関数の対称式のMaxminの扱い方は？" },
      { number: 19, level: 3, checkPoint: "どのような式が与えられた時にコーシーシュワルツの不等式を考慮する？" },
      { number: 20, level: 4, checkPoint: "3変数関数のMaxminで何もうまく行かなくて困った時に考えてみたい方針は？" },
    ],
  },
  "1a-3": {
    title: "技1A 第3章（方程式・不等式）",
    problems: [
      { number: 1, level: 1, checkPoint: "通常の2次方程式の解の個数の求め方は？" },
      { number: 2, level: 2, checkPoint: "方程式の共通解の解法は？ また、連立方程式を処理した後、最後に確認すべきことは？" },
      { number: 3, level: 2, checkPoint: "実数係数の方程式が虚数解をもつときの扱いは？" },
      { number: 4, level: 3, checkPoint: "方程式で有理数解もつときたら？また、代入した後の変形の仕方は？" },
      { number: 5, level: 1, checkPoint: "解の差・解の比など、特殊な解の条件が与えられたら？" },
      { number: 6, level: 2, checkPoint: "α , βを2解にもつ2次方程式の作り方は？" },
      { number: 7, level: 3, checkPoint: "次数が高く代入計算が面倒なときの工夫の仕方は？" },
      { number: 8, level: 2, checkPoint: "3次方程式における解と係数の関係は？" },
      { number: 9, level: 1, checkPoint: "2文字の対称式からなる連立方程式の解き方は？" },
      { number: 10, level: 2, checkPoint: "3文字の対称式からなる連立方程式の解き方は？" },
      { number: 11, level: 3, checkPoint: "対称性が微妙に崩れた3文字の連立方程式の解き方は？" },
      { number: 12, level: 4, checkPoint: "サイクリックな連立方程式の解法は？" },
      { number: 13, level: 1, checkPoint: "方程式の問題でまず最初に確認すべきことは？" },
      { number: 14, level: 3, checkPoint: "方程式の解の個数をグラフにより考える際のポイントは？" },
      { number: 15, level: 2, checkPoint: "2次方程式の解の配置(範囲つき解の個数)は何に注目して立式する？" },
      { number: 16, level: 3, checkPoint: "どのような方程式なら直線分離で考えることができる？" },
      { number: 17, level: 2, checkPoint: "方程式で置換した時に忘れずにすべきことは？また、解の対応関係の調べ方は？" },
      { number: 18, level: 3, checkPoint: "相反方程式の式処理は？解の対応でt=g(x)のグラフが描きづらいときの工夫の仕方は？" },
      { number: 19, level: 3, checkPoint: "方程式の解の範囲を考えるには？" },
      { number: 20, level: 4, checkPoint: "方程式の解の範囲を、解いたりグラフで考えたりしづらい場合に考慮する方針は？" },
      { number: 21, level: 1, checkPoint: "不等式の解はグラフでどのように扱える？" },
      { number: 22, level: 2, checkPoint: "不等式の問題でまず最初に確認すべきことは？" },
      { number: 23, level: 3, checkPoint: "不等式の問題で因数分解できないときに考える方針は？" },
      { number: 24, level: 4, checkPoint: "式変形では扱いづらい不等式の扱いとして、考慮したい発想は？" },
      { number: 25, level: 2, checkPoint: "「すべてのxでf(x)>a」 ときたら…？" },
      { number: 26, level: 2, checkPoint: "「あるxでf(x)>a」 ときたら…？" },
      { number: 27, level: 3, checkPoint: "「すべての組x<sub>1</sub>, x<sub>2</sub>でf(x<sub>1</sub>)≦g(x<sub>2</sub>)」 ときたら…？" },
      { number: 28, level: 3, checkPoint: "「ある組x<sub>1</sub>, x<sub>2</sub>でf(x<sub>1</sub>)≦g(x<sub>2</sub>)」 ときたら…？" },
    ],
  },
  "2b-3": {
    title: "技2B 第3章（三角関数）",
    problems: [
      { number: 1, level: 1, checkPoint: "三角関数の値の定義は？" },
      { number: 2, level: 1, checkPoint: "cos(θ+π)=？、sin(θ+π/2)=？、cos(-θ)=？などすぐに言える？" },
      { number: 3, level: 2, checkPoint: "三角関数のグラフの描き方、周期の求め方は？" },
      { number: 4, level: 3, checkPoint: "三角関数の値が有名角ではないときの評価の仕方は？" },
      { number: 5, level: 1, checkPoint: "三角関数の相互関係とは？" },
      { number: 6, level: 3, checkPoint: "tan<sup>2</sup>θで表せるのはどんな式？" },
      { number: 7, level: 1, checkPoint: "sin, cos の対称式の扱いは？" },
      { number: 8, level: 2, checkPoint: "t=sinx+cosxと置換した後にやるべきこと2つは？" },
      { number: 9, level: 1, checkPoint: "1つのsinにまとまった三角方程式の解き方は？" },
      { number: 10, level: 2, checkPoint: "角・種がそろったら、三角方程式はどのように扱える？" },
      { number: 11, level: 1, checkPoint: "三角方程式を解く上でまず考慮すべき方針は？" },
      { number: 12, level: 3, checkPoint: "三角不等式の成立条件で置換したうえでの注意点は？" },
      { number: 13, level: 1, checkPoint: "加法定理、ちゃんと覚えている？" },
      { number: 14, level: 2, checkPoint: "加法定理より展開した式の値をうまく求めるには？" },
      { number: 15, level: 2, checkPoint: "2直線のなす角を求める公式とその作り方は？" },
      { number: 16, level: 3, checkPoint: "なす(鋭)角が最大となるとは、何が最大となるということ？ 正の逆数の和の(Max)minときたら？" },
      { number: 17, level: 1, checkPoint: "2倍角、3倍角、半角、全部言える？" },
      { number: 18, level: 2, checkPoint: "cos36°の求め方、知ってる？" },
      { number: 19, level: 3, checkPoint: "tanθ/2 = t  として sinθ, cosθは t でどのように表せる？" },
      { number: 20, level: 3, checkPoint: "三角関数の式を強引に整関数を含む式で置換する方法とは？" },
      { number: 21, level: 1, checkPoint: "sinとcos の1次式の和・差はどう扱う？" },
      { number: 22, level: 2, checkPoint: "合成したときに出る角αが有名角ではなくても扱える？" },
      { number: 23, level: 2, checkPoint: "三角関数の2次同次式の扱いは？ (※本ではLv.3になっていますが例外的にLv.2として扱います)" },
      { number: 24, level: 4, checkPoint: "sin,cosの1次式について、合成以外の解法とは？" },
      { number: 25, level: 1, checkPoint: "和積公式、積和公式、作れる？" },
      { number: 26, level: 2, checkPoint: "和積公式はどのような場面で活躍する？" },
      { number: 27, level: 3, checkPoint: "sin⚫︎=sin▲,  sin⚫︎=cos▲ など、解ける？" },
      { number: 28, level: 3, checkPoint: "三角形の内角についての式処理で有名な式処理とは？" },
      { number: 29, level: 2, checkPoint: "三角方程式の解の個数はどのように考える？" },
      { number: 30, level: 2, checkPoint: "三角方程式で置換したら、何を考える？" },
      { number: 31, level: 3, checkPoint: "三角関数の対称式を含む方程式で置換したら、解の対応はどのように考える？" },
      { number: 32, level: 4, checkPoint: "cos 2/7πを解にもつ方程式を作れる？同様に、cos 4/7π, cos 6/7πを解にもつ方程式を作れる？" },
      { number: 33, level: 2, checkPoint: "仰角、俯角の意味は？" },
      { number: 34, level: 2, checkPoint: "図形量のMax,minの代数的解法とは？" },
      { number: 35, level: 3, checkPoint: "図形量の数式化において用いることができる公式たちは？" },
      { number: 36, level: 4, checkPoint: "三角形の内角についての式処理で、積から出発する場合に考えるのは？" },
    ],
  },
  "2b-4": {
    title: "技2B 第4章（指数・対数関数）",
    problems: [
      { number: 1, level: 1, checkPoint: "指数法則は大丈夫？" },
      { number: 2, level: 1, checkPoint: "対数法則は大丈夫？" },
      { number: 3, level: 2, checkPoint: "a<sup>x</sup>=b<sup>y</sup> の形で、底が揃いにくいような式の扱いは？" },
      { number: 4, level: 3, checkPoint: "無理数であることは証明はどのように行う？" },
      { number: 5, level: 1, checkPoint: "y=a<sup>x</sup>のグラフ、y=log<sub>a</sub> xのグラフの概形は？" },
      { number: 6, level: 2, checkPoint: "指数対数の大小比較のコツは？" },
      { number: 7, level: 3, checkPoint: "文字定数入りの指数・対数の大小比較について、まず行うべきことは？" },
      { number: 8, level: 4, checkPoint: "対数のグラフの凸性をイメージして値を評価することができる？" },
      { number: 9, level: 1, checkPoint: "対数の式処理のポイントは？" },
      { number: 10, level: 2, checkPoint: "指数の相反式の扱い方は？" },
      { number: 11, level: 2, checkPoint: "対数の２変数関数の最大最小で、最優先したい発想とは？" },
      { number: 12, level: 3, checkPoint: "対数の２変数関数の最大最小で、文字消去が難しいときに考えるべき発想とは？" },
      { number: 13, level: 1, checkPoint: "指数の式処理のポイントは？" },
      { number: 14, level: 1, checkPoint: "対数の不等式で、真数の比較をする上で注意すべき点は？" },
      { number: 15, level: 2, checkPoint: "対数の不等式で、底に文字定数を含む場合に注意すべき点は？" },
      { number: 16, level: 3, checkPoint: "底にも真数にも変数を含む対数の式だが、どのような不等式条件に注意する？" },
      { number: 17, level: 2, checkPoint: "不等式の成立条件ときたら？対数の不等式で底に文字定数を含む場合に注意すべき点は？" },
      { number: 18, level: 2, checkPoint: "方程式の解の個数ときたら？ (本問で真数条件を一部無視できる理由は？)" },
      { number: 19, level: 3, checkPoint: "指数の方程式で置換したときに考えないといけないことは？" },
      { number: 20, level: 4, checkPoint: "解の対応でt=g(x)のグラフが描きづらいときの工夫の仕方は？" },
      { number: 21, level: 2, checkPoint: "桁数の求め方は？" },
      { number: 22, level: 2, checkPoint: "小数第⚫︎位に初めて現れる数の求め方は？" },
      { number: 23, level: 3, checkPoint: "大きな値の不等式 (本問だと2<sup>n</sup> >1億5千万) を評価するために有用なこととは？" },
      { number: 24, level: 4, checkPoint: "常用対数の値の評価は、どのような方針で行うと上手くいく？" },
    ],
  },
  "2b-5": {
    title: "技2B 第5章（微分法）",
    problems: [
      { number: 1, level: 1, checkPoint: "平均変化率とは？微分係数の定義は？" },
      { number: 2, level: 2, checkPoint: "微分係数の定義は？ 微分係数の定義を利用した極限値の計算上のポイントは？" },
      { number: 3, level: 1, checkPoint: "導関数の定義は？" },
      { number: 4, level: 3, checkPoint: "変化率とは？" },
      { number: 5, level: 1, checkPoint: "接線と曲線のもう１つの交点を求める際の計算上のポイントは？" },
      { number: 6, level: 2, checkPoint: "共通接線（接点異なる）の立式は？" },
      { number: 7, level: 2, checkPoint: "共通接線（接点同じ）の立式は？" },
      { number: 8, level: 3, checkPoint: "4次曲線の複接線の(比較的楽な)立式の仕方は？" },
      { number: 9, level: 1, checkPoint: "面倒な極値計算のやり方は？" },
      { number: 10, level: 2, checkPoint: "3次関数が極値もつための条件は？" },
      { number: 11, level: 2, checkPoint: "「y=f(x)がx=aで極値もつ」の数式化と、立式の際の注意点は？" },
      { number: 12, level: 3, checkPoint: "極値の差の数式化はどのようにする？(別解として、1/6公式を利用する方法もある)" },
      { number: 13, level: 1, checkPoint: "２変数関数の最大最小でまず考えることは？" },
      { number: 14, level: 2, checkPoint: "文字定数含む3次関数のMaxminの場合分けのの際、グラフの概形として注意すべき点は？" },
      { number: 15, level: 3, checkPoint: "文字定数含む3次関数のMaxminの場合分けのポイントは？" },
      { number: 16, level: 4, checkPoint: "変曲点とは？ 3次関数の変曲点についての図形的性質とは？" },
      { number: 17, level: 2, checkPoint: "3次方程式の解の個数でまず考えることは？" },
      { number: 18, level: 1, checkPoint: "3次方程式の解の個数で因数分解の次に考えることは？" },
      { number: 19, level: 2, checkPoint: "3次方程式の解の個数でx軸相手に比べる際の立式の仕方は？" },
      { number: 20, level: 3, checkPoint: "3変数関数の対称式のMaxminを求める問題では、結局何に帰着させて考える？" },
      { number: 21, level: 2, checkPoint: "接線の本数問題の立式の仕方は？" },
      { number: 22, level: 3, checkPoint: "接線の本数問題の立式の仕方は？ちなみに、接線の本数が変化する境界線は知ってる？" },
      { number: 23, level: 3, checkPoint: "共通接線の本数は、接点に文字おけば連立方程式の解の個数に帰着されるが、放物線相手だとどうするのが楽？" },
      { number: 24, level: 4, checkPoint: "4次関数での接線の本数を考える上で注意すべきこととは？" },
      { number: 25, level: 1, checkPoint: "3次不等式を解くには？" },
      { number: 26, level: 2, checkPoint: "不等式の証明の基本的な考え方は？" },
      { number: 27, level: 3, checkPoint: "不等式の成立条件で関数のMaxminを考える際、文字定数含む場合に気をつけることは？" },
      { number: 28, level: 3, checkPoint: "「すべての組x<sub>1</sub>, x<sub>2</sub>でf(x<sub>1</sub>)≧g(x<sub>2</sub>)」 ときたら…？" },
    ],
  },
  "2b-6": {
    title: "技2B 第6章（積分法）",
    problems: [
      { number: 1, level: 1, checkPoint: "定積分における、偶関数・奇関数の性質とは？" },
      { number: 2, level: 2, checkPoint: "カタマリ積分とはどんな公式？また、1/6公式とはどんな公式？" },
      { number: 3, level: 3, checkPoint: "積分の各種公式 (1/6公式、1/12公式、1/30公式)の証明における式変形のPointは？" },
      { number: 4, level: 3, checkPoint: "絶対値つき定積分のPointは？" },
      { number: 5, level: 1, checkPoint: "積分方程式（区間が変数）の解法は？" },
      { number: 6, level: 2, checkPoint: "積分方程式（区間が定数）の解法は？" },
      { number: 7, level: 3, checkPoint: "積分方程式（融合パターン）の解法は？" },
      { number: 8, level: 4, checkPoint: "関数がnの値で規則的に変化する問題(関数列)の解法のポイントは？" },
      { number: 9, level: 1, checkPoint: "面積を求める立式の仕方は？" },
      { number: 10, level: 1, checkPoint: "1/6公式が使える面積の形 のパターンは？（全部で3パターン）" },
      { number: 11, level: 2, checkPoint: "1/6公式が使える面積の形 のパターンは？（全部で3パターン）" },
      { number: 12, level: 3, checkPoint: "1/6公式が使える面積の形 のパターンは？（全部で3パターン）" },
      { number: 13, level: 1, checkPoint: "カタマリ積分が使える面積の形 のパターンは？" },
      { number: 14, level: 2, checkPoint: "円がらみの面積を求める方法は？" },
      { number: 15, level: 3, checkPoint: "3次関数と接線で囲まれた面積の計算上のポイントは？" },
      { number: 16, level: 3, checkPoint: "4次関数と複接線で囲まれた面積の計算上のポイントは？" },
      { number: 17, level: 2, checkPoint: "面積を立式する上で計算を楽にするためのポイントとは？" },
      { number: 18, level: 2, checkPoint: "放物線と直線で囲まれた面積の最小値はどのような方針で求める？" },
      { number: 19, level: 3, checkPoint: "絶対値がらみの放物線に関する面積をどのように数式化するのが楽？" },
      { number: 20, level: 4, checkPoint: "「2つの面積が等しい」をどのように変形して計算するのが楽？" },
    ],
  },
  "1a-5": {
    title: "技1A 第5章（三角比・図形）",
    problems: [
      { number: 1, level: 1, checkPoint: "正弦定理の有名な使い所は？" },
      { number: 2, level: 2, checkPoint: "三角形の内角のsinの比が与えられた時にやるべきことは？" },
      { number: 3, level: 1, checkPoint: "余弦定理の有名な使い所は？" },
      { number: 4, level: 2, checkPoint: "三角形の形状決定の定石は？" },
      { number: 5, level: 1, checkPoint: "三角形の内接円の半径を求めるには？" },
      { number: 6, level: 2, checkPoint: "角の二等分線の長さ、垂線の長さの立式は？" },
      { number: 7, level: 2, checkPoint: "ヘロンの公式とは？" },
      { number: 8, level: 3, checkPoint: "四角形の対角線の長さとなす角から四角形の面積を求める公式は？" },
      { number: 9, level: 1, checkPoint: "角の二等分線の性質とは？外角でもいける？" },
      { number: 10, level: 2, checkPoint: "三角形の成立条件とは？また、鋭角・鈍角三角形の成立条件は？" },
      { number: 11, level: 2, checkPoint: "チェバの定理、メネラウスの定理とは？" },
      { number: 12, level: 3, checkPoint: "1つの直線上にあることの証明、1点で交わることの証明に用いることがある定理は？" },
      { number: 13, level: 1, checkPoint: "円周角の定理とは？（中心角との関係含め）" },
      { number: 14, level: 2, checkPoint: "方べきの定理とは？またその本質は？" },
      { number: 15, level: 2, checkPoint: "接弦定理とは？" },
      { number: 16, level: 3, checkPoint: "共通内接線・外接線の長さを求めるうえでのポイントは？" },
      { number: 17, level: 1, checkPoint: "円に内接する四角形の性質とは？" },
      { number: 18, level: 2, checkPoint: "円に内接する四角形の対角線の長さを求めるには？" },
      { number: 19, level: 3, checkPoint: "トレミーの定理とは？" },
      { number: 20, level: 4, checkPoint: "ヘロンの公式の拡張内接四角形バージョンの公式とは？（”ブラーマグプタの公式”という）" },
      { number: 21, level: 2, checkPoint: "重心の性質は？" },
      { number: 22, level: 2, checkPoint: "正三角形についての重要な五心の性質は？" },
      { number: 23, level: 3, checkPoint: "垂心の性質と、その証明方法は？" },
      { number: 24, level: 4, checkPoint: "オイラー線の性質とその証明方法は？" },
      { number: 25, level: 1, checkPoint: "立体図形の断面の取り方で重要なテクニックは？" },
      { number: 26, level: 2, checkPoint: "正四面体の内接球の半径の求め方は？ (相似を使う解法でもできる？)" },
      { number: 27, level: 3, checkPoint: "正四面体の外接球の半径の求め方は？" },
      { number: 28, level: 4, checkPoint: "立体図形の断面の取り方で重要なテクニックは？ また、等面四面体は何に埋め込める？" },
      { number: 29, level: 3, checkPoint: "三垂線の定理とは？" },
      { number: 30, level: 2, checkPoint: "正多面体の頂点の数、辺の数の求め方は？" },
      { number: 31, level: 3, checkPoint: "オイラーの多面体定理とは？サッカーボールにおいて頂点の個数の表現の仕方の工夫は？" },
      { number: 32, level: 4, checkPoint: "正多面体は5種類しかないことを証明できる？" },
    ],
  },
  "2b-2": {
    title: "技2B 第2章（図形と式）",
    problems: [
      { number: 1, level: 1, checkPoint: "内分点、外分点の座標の公式は？" },
      { number: 2, level: 1, checkPoint: "重心の座標の公式は？" },
      { number: 3, level: 2, checkPoint: "四角形が平行四辺形となるための条件は？ (参考：ベクトルでもできる？)" },
      { number: 4, level: 3, checkPoint: "座標設定をするうえでのポイントは？" },
      { number: 5, level: 1, checkPoint: "不動点(常に通る定点)の求め方は？" },
      { number: 6, level: 3, checkPoint: "外心の座標の求め方は？2通りの方法でいける？" },
      { number: 7, level: 2, checkPoint: "直線の平行条件、垂直条件は？ (一般形でも覚えてる？)" },
      { number: 8, level: 4, checkPoint: "x,y切片を利用した直線の方程式は？" },
      { number: 9, level: 1, checkPoint: "点と直線の距離公式とは？" },
      { number: 10, level: 2, checkPoint: "三角形の面積公式、座標verは？" },
      { number: 11, level: 2, checkPoint: "直線の対称点の求め方は？折れ線の長さの最小値を求める方法は？" },
      { number: 12, level: 3, checkPoint: "内心の座標の求め方は？2通りの方法でいける？" },
      { number: 13, level: 1, checkPoint: "円の方程式の標準形、一般形とは？" },
      { number: 14, level: 2, checkPoint: "円を対称移動した円を求める方針は？" },
      { number: 15, level: 1, checkPoint: "円と直線の関係の数式化はどうする？2通りの方法でいける？" },
      { number: 16, level: 3, checkPoint: "円を切り取る弦の長さを立式するうえでのポイントは？" },
      { number: 17, level: 1, checkPoint: "円の接線の方程式は？" },
      { number: 18, level: 2, checkPoint: "円の接線を求める方法は？2通りの方法でいける？" },
      { number: 19, level: 3, checkPoint: "極線とは？極線の方程式はどのような形？また、その証明方法は？" },
      { number: 20, level: 4, checkPoint: "円の共通内/外接線の求め方は？図形的・代数的いずれでも求められる？" },
      { number: 21, level: 2, checkPoint: "円と円の位置関係、整理できている？" },
      { number: 22, level: 3, checkPoint: "2円の交点を通る円または直線の式は？" },
      { number: 23, level: 3, checkPoint: "円と放物線の共有点の個数の数式化は？ また、y の2次方程式で考えるうえでの注意点は？" },
      { number: 24, level: 4, checkPoint: "円と放物線の共有点の個数問題の解法は？(少なくとも2つは挙げれる？)" },
      { number: 25, level: 2, checkPoint: "軌跡の幾何的解法とは？また、どういう時に使える考え方？" },
      { number: 26, level: 2, checkPoint: "軌跡の代数的解法の流れは？" },
      { number: 27, level: 2, checkPoint: "軌跡の代数的解法において、別の動点に文字おいた時の扱いは？" },
      { number: 28, level: 3, checkPoint: "半直線上でOP・OQ=⚫︎を満たす点の軌跡(“反転”という)の考え方は？" },
      { number: 29, level: 2, checkPoint: "軌跡を求める上で最後に注意すべきことは？" },
      { number: 30, level: 2, checkPoint: "点(s+t , st)の存在範囲の求め方と注意点は？" },
      { number: 31, level: 3, checkPoint: "2直線の交点の軌跡で、一般的に交点をパラメータ表示するよりも楽な解法は？" },
      { number: 32, level: 4, checkPoint: "円外の点から引いた2接線の接点の中点 (の軌跡)の求め方は？" },
      { number: 33, level: 1, checkPoint: "正領域・負領域を用いて領域図示するコツは？" },
      { number: 34, level: 2, checkPoint: "グラフを描く上で、これがある場合は利用すると楽になる。何？" },
      { number: 35, level: 3, checkPoint: "直線と線分の共有点の問題で用いると楽な考え方は？" },
      { number: 36, level: 4, checkPoint: "直線を除く曲線と線分の共有点の問題は、どのように考えて立式する？" },
      { number: 37, level: 2, checkPoint: "領域内の最大最小問題の解法は？" },
      { number: 38, level: 2, checkPoint: "領域内の最大最小問題の解法は？（文章題もきちんと数式化できる？）" },
      { number: 39, level: 3, checkPoint: "領域内の最大最小問題で文字定数を含むときの場合分けのコツは？" },
      { number: 40, level: 4, checkPoint: "図示可能な2変数関数のMax・minを求める基本的な方針は？" },
      { number: 41, level: 2, checkPoint: "直線の通過領域の問題の解法とは？" },
      { number: 42, level: 2, checkPoint: "図形の通過領域の問題の解法とは？" },
      { number: 43, level: 3, checkPoint: "ファクシミリの原理とは？" },
      { number: 44, level: 4, checkPoint: "包絡線とは？" },
    ],
  },
  "2b-9": {
    title: "技2B 第9章（ベクトル）",
    problems: [
      { number: 1, level: 1, checkPoint: "ベクトルの加法、減法の公式とその意義は？" },
      { number: 2, level: 3, checkPoint: "正五角形の辺と対角線の長さや向きの関係は？" },
      { number: 3, level: 1, checkPoint: "内分点の公式、外分点の公式、OK？" },
      { number: 4, level: 2, checkPoint: "内分点から点の位置を求める有名変形、OK？" },
      { number: 5, level: 1, checkPoint: "ベクトルでなす角ときたらどう数式化する？" },
      { number: 6, level: 2, checkPoint: "絶対値の処理の仕方は？" },
      { number: 7, level: 3, checkPoint: "内積の図形的な意味合いとは？" },
      { number: 8, level: 4, checkPoint: "正射影ベクトルとは？" },
      { number: 9, level: 1, checkPoint: "成分公式（大きさ、内積など）、OK？" },
      { number: 10, level: 2, checkPoint: "なす角・垂直の数式化は？" },
      { number: 11, level: 2, checkPoint: "平行条件の数式化は？" },
      { number: 12, level: 2, checkPoint: "三角形の面積公式（ベクトル・成分）OK？" },
      { number: 13, level: 1, checkPoint: "直線のベクトル方程式とは？" },
      { number: 14, level: 2, checkPoint: "直線上の数式化とは？" },
      { number: 15, level: 2, checkPoint: "法線ベクトルを利用した直線の数式化とは？" },
      { number: 16, level: 3, checkPoint: "角の二等分線の数式化とは？" },
      { number: 17, level: 2, checkPoint: "位置ベクトルの基本的発想は？(本問のようにうまく処理することもあると理解しておく)" },
      { number: 18, level: 2, checkPoint: "同一直線上にあることを示すには？" },
      { number: 19, level: 2, checkPoint: "2直線の交点の位置ベクトルの求め方は？幾何的な別解でも解ける？" },
      { number: 20, level: 3, checkPoint: "垂線の足の数式化はどんな2式を立てる？" },
      { number: 21, level: 1, checkPoint: "円のベクトル方程式とは？" },
      { number: 22, level: 2, checkPoint: "外接円上にある点の数式化の方法は？" },
      { number: 23, level: 3, checkPoint: "円の接線(直線)のベクトル方程式は、何に注目して立式すればよい？" },
      { number: 24, level: 4, checkPoint: "円と角の二等分線の交点はどう立式すればよい？" },
      { number: 25, level: 2, checkPoint: "内心の位置ベクトルの求め方2通りは？" },
      { number: 26, level: 3, checkPoint: "外心の位置ベクトルの求め方2通りは？" },
      { number: 27, level: 3, checkPoint: "傍心の図形的な性質は？位置ベクトルはどのように求める？ (※本ではLv.4になっていますが例外的にLv.3として扱います)" },
      { number: 28, level: 4, checkPoint: "垂心の位置ベクトルは外心を始点にするとどのように表せる？また、それを証明できる？" },
      { number: 29, level: 2, checkPoint: "<span class=\"vec\">OP</span>=s<span class=\"vec\">OA</span>+t<span class=\"vec\">OB</span> のとき、s+t=1を満たす点Pの存在範囲は？ また、斜交座標でのイメージは？" },
      { number: 30, level: 3, checkPoint: "<span class=\"vec\">OP</span>=s<span class=\"vec\">OA</span>+t<span class=\"vec\">OB</span> のとき、s+t=1, s≧0, t≧0を満たす点Pの存在範囲は？ また、斜交座標でのイメージは？" },
      { number: 31, level: 3, checkPoint: "<span class=\"vec\">OP</span>=s<span class=\"vec\">OA</span>+t<span class=\"vec\">OB</span> のとき、s+t≦1, s≧0, t≧0を満たす点Pの存在範囲は？ また、斜交座標でのイメージは？" },
      { number: 32, level: 4, checkPoint: "<span class=\"vec\">OP</span>=s<span class=\"vec\">OA</span>+t<span class=\"vec\">OB</span> のとき、0≦s≦1, 0≦t≦1を満たす点Pの存在範囲は？ また、斜交座標でのイメージは？" },
      { number: 33, level: 1, checkPoint: "空間座標　まずは綺麗に図を描ける？" },
      { number: 34, level: 2, checkPoint: "空間座標における2点間距離公式は？" },
      { number: 35, level: 3, checkPoint: "4点を通る球の中心の座標の求め方は？" },
      { number: 36, level: 4, checkPoint: "正四面体の残り1個の頂点の座標の求め方は？" },
      { number: 37, level: 1, checkPoint: "空間座標における内積の公式は？" },
      { number: 38, level: 2, checkPoint: "なす角の数式化と来たら？" },
      { number: 39, level: 2, checkPoint: "(空間座標における)三角形の面積公式は？" },
      { number: 40, level: 3, checkPoint: "2つのベクトルに垂直なベクトルの求め方は？また、外積ベクトルを利用した方法は？" },
      { number: 41, level: 1, checkPoint: "空間座標における直線の方程式とは？(通る1点と方向ベクトルを用いて)" },
      { number: 42, level: 1, checkPoint: "空間座標における直線の方程式とは？(通る2点を用いて)" },
      { number: 43, level: 2, checkPoint: "空間座標における直線と平面の交点はどう求める？" },
      { number: 44, level: 3, checkPoint: "2直線上の2点間の距離の最小値の求め方2通りは？" },
      { number: 45, level: 1, checkPoint: "空間座標における球面の方程式とは？" },
      { number: 46, level: 2, checkPoint: "球面のベクトル方程式とは？" },
      { number: 47, level: 3, checkPoint: "平面α上の点Aを中心とする円の、円上の直交する2つのベクトル <span class=\"vec\">b</span>, <span class=\"vec\">c</span> を用いたベクトル方程式は？" },
      { number: 48, level: 4, checkPoint: "円錐面のベクトル方程式とは？" },
      { number: 49, level: 1, checkPoint: "空間座標における平面の方程式と、その求め方2通りとは？" },
      { number: 50, level: 2, checkPoint: "空間座標における直線と平面の交点はどう求める？" },
      { number: 51, level: 3, checkPoint: "平面の方程式 (切片形) とは？ 点と平面の距離公式とは？" },
      { number: 52, level: 3, checkPoint: "球面と平面との交わりの円はどのように求める？" },
      { number: 53, level: 2, checkPoint: "空間ベクトルにおける基準ベクトルとは？交点はどのように求める？" },
      { number: 54, level: 2, checkPoint: "直線と平面の交点はどう求める？" },
      { number: 55, level: 3, checkPoint: "四面体の点の位置の決定問題の方針は？" },
      { number: 56, level: 4, checkPoint: "四面体の体積比を求めるために必要な情報と、そのために意識する式変形とは？" },
      { number: 57, level: 2, checkPoint: "垂線の足の数式化、どうする？" },
      { number: 58, level: 2, checkPoint: "ベクトルが平面と垂直であるとき、どのように数式化する？" },
      { number: 59, level: 3, checkPoint: "点から三角形の内部に降ろした垂線の足は、どのように数式化する？" },
      { number: 60, level: 4, checkPoint: "外積ベクトルを利用した四面体の体積の求め方は？" },
    ],
  },
  "1a-6": {
    title: "技1A 第6章（場合の数）",
    problems: [
      { number: 1, level: 1, checkPoint: "複数の集合を整理するには？ド・モルガンの法則とは？" },
      { number: 2, level: 2, checkPoint: "複数の集合を整理するには？また、倍数の個数の求め方は？(詳しくは整数)" },
      { number: 3, level: 3, checkPoint: "3つの集合のベン図描き方および要素の個数の求め方は？" },
      { number: 4, level: 4, checkPoint: "包除原理とは？" },
      { number: 5, level: 2, checkPoint: "樹形図を書く上でのポイントは？" },
      { number: 6, level: 2, checkPoint: "2種類の要素で定まるものを書き出す時のコツは？" },
      { number: 7, level: 2, checkPoint: "積が偶数となる場合の数はどう求めるのが楽？" },
      { number: 8, level: 2, checkPoint: "場合を分けて数える時のポイントは？" },
      { number: 9, level: 2, checkPoint: "隣り合う、隣り合わない　順列の求め方は？" },
      { number: 10, level: 3, checkPoint: "条件がついた順列の総数を求めるうえでのポイントは？" },
      { number: 11, level: 2, checkPoint: "重複順列とは？また、その求め方は？" },
      { number: 12, level: 3, checkPoint: "部分集合の総数の求め方は？" },
      { number: 13, level: 1, checkPoint: "選び方の総数はどう求める？nCrの定義式は？" },
      { number: 14, level: 2, checkPoint: "頂点を選んで作る三角形の総数を求める上でのコツは？" },
      { number: 15, level: 2, checkPoint: "要素をグループ分けして求める考え方、できる？" },
      { number: 16, level: 3, checkPoint: "頂点を選んで作る鋭角三角形の総数を求める方法は？" },
      { number: 17, level: 1, checkPoint: "同じものを含む順列の場合分け、どうする？" },
      { number: 18, level: 2, checkPoint: "「この順で並ぶ」の数え方は？" },
      { number: 19, level: 2, checkPoint: "最短経路の問題の数え方は？場合分けの方法は？" },
      { number: 20, level: 4, checkPoint: "カタラン数とは？" },
      { number: 21, level: 1, checkPoint: "円順列、じゅず順列の考え方は？" },
      { number: 22, level: 2, checkPoint: "立方体の色塗りの考え方は？”固定する”ってどういうこと？" },
      { number: 23, level: 2, checkPoint: "同じものを含む円順列、どのように考える？" },
      { number: 24, level: 3, checkPoint: "全てのものに同じものを含む円順列、どのように考える？" },
      { number: 25, level: 1, checkPoint: "重複組合せとは？何を何に対応させて考える？" },
      { number: 26, level: 3, checkPoint: "大小関係が定められた順列の求め方は？等号・不等号の有無でどう変わる？" },
      { number: 27, level: 2, checkPoint: "整数解の個数の求め方は？" },
      { number: 28, level: 4, checkPoint: "領域図示が可能な不定方程式または不等式の整数解の個数は、どのように考えられる？" },
      { number: 29, level: 1, checkPoint: "分配の問題の4つパターンとは？" },
      { number: 30, level: 2, checkPoint: "区別あるものを区別ある組に分ける時、組の人数がわからない場合はどうする？" },
      { number: 31, level: 3, checkPoint: "区別あるものを区別ない組に分ける時、組の人数がわからない場合はどうする？" },
      { number: 32, level: 2, checkPoint: "区別ないものを分けるにはどうする？" },
      { number: 33, level: 1, checkPoint: "二項定理の一般項は？" },
      { number: 34, level: 2, checkPoint: "多項定理の一般項は？" },
      { number: 35, level: 3, checkPoint: "二項係数の性質3つ、ちゃんと言える？(組合せ論的理解が覚えやすい)" },
      { number: 36, level: 4, checkPoint: "二項係数の和はどう求める？また、求めにくいものは何を利用する？" },
      { number: 37, level: 2, checkPoint: "場合の数で漸化式立てる上でのポイントは？" },
      { number: 38, level: 3, checkPoint: "場合の数で漸化式立てる上でのポイント 2つ目は？" },
      { number: 39, level: 3, checkPoint: "場合の数で漸化式立てる上でのポイント 2つ目は？" },
      { number: 40, level: 4, checkPoint: "どの要素も自身の元の番号と同じ位置にならない並び方(“完全順列”という)の漸化式の立て方は？" },
    ],
  },
  "1a-7": {
    title: "技1A 第7章（確率）",
    problems: [
      { number: 1, level: 1, checkPoint: "2個のサイコロの出た目はどう整理するのがいい？全事象が21通りではダメな理由は？" },
      { number: 2, level: 3, checkPoint: "同じ色の球を含む確率ではどのように考える？" },
      { number: 3, level: 2, checkPoint: "余事象はどのような時に考える？" },
      { number: 4, level: 2, checkPoint: "和事象の確率を求める際の注意点は？" },
      { number: 5, level: 1, checkPoint: "条件つき確率の定義は？求める公式は？" },
      { number: 6, level: 2, checkPoint: "条件つき確率を整理する上で役立つ方法は？" },
      { number: 7, level: 3, checkPoint: "条件つき確率と積事象の確率の関係は？" },
      { number: 8, level: 4, checkPoint: "事象AとBが独立とは？従属とは？" },
      { number: 9, level: 1, checkPoint: "反復試行の確率とは？求め方は？" },
      { number: 10, level: 2, checkPoint: "試行の終了条件に事象の起こる確率が含まれているとき、注意することは？" },
      { number: 11, level: 2, checkPoint: "サイコロ・コインなどにより点を移動させる問題での考え方は？" },
      { number: 12, level: 3, checkPoint: "確率の最大値を求める方法は？" },
      { number: 13, level: 2, checkPoint: "大小関係が定められた順列の求め方は？等号・不等号の有無でどう変わる？" },
      { number: 14, level: 2, checkPoint: "サイコロの出た目の最大値・最小値についての確率の求め方は？" },
      { number: 15, level: 3, checkPoint: "サイコロの出た目の最大値=Mかつ 最小値=m となる確率は、どのように考える？" },
      { number: 16, level: 4, checkPoint: "サイコロの出た目の出た目の積が⚫︎の倍数 ときたら、事象をどのように取って、どんな式で考える？" },
      { number: 17, level: 2, checkPoint: "玉・くじ・カード型の同時抽出の考え方は？" },
      { number: 18, level: 2, checkPoint: "玉・くじ・カード型の復元抽出の考え方は？" },
      { number: 19, level: 3, checkPoint: "玉・くじ・カード型の非復元抽出の考え方は？" },
      { number: 20, level: 3, checkPoint: "変則的な抽出で注意することは？" },
      { number: 21, level: 1, checkPoint: "ジャンケンの確率の立式の仕方は？" },
      { number: 22, level: 2, checkPoint: "ジャンケンであいこになる確率はどう求める？ 2パターンの求め方でいける？" },
      { number: 23, level: 3, checkPoint: "変則的なジャンケンになった時の立式の仕方は？" },
      { number: 24, level: 4, checkPoint: "じゃんけんの反復はどのように考える？ただし注意すべき点は？" },
      { number: 25, level: 1, checkPoint: "期待値の定義は？何を描いて求めるとよい？" },
      { number: 26, level: 2, checkPoint: "期待値を求める際に確率を求めるのが面倒なものに対する工夫は？" },
      { number: 27, level: 3, checkPoint: "期待値を求める際に二項係数の和が出てきた際はどうする？" },
      { number: 28, level: 4, checkPoint: "期待値の和・実数倍についての性質は？" },
      { number: 29, level: 1, checkPoint: "確率漸化式を立式する上でのPointは？" },
      { number: 30, level: 2, checkPoint: "確率漸化式で、n回目に起こる全ての事象についての確率の関係式は？" },
      { number: 31, level: 4, checkPoint: "確率漸化式で、偶数回目と奇数回目で状況が異なる時の立式はどうする？" },
      { number: 32, level: 3, checkPoint: "確率漸化式で、(状態推移図以外に) 立式のうえでのPointは？" },
    ],
  },
  "1a-8": {
    title: "技1A 第8章（整数）",
    problems: [
      { number: 1, level: 1, checkPoint: "2,3,4,5,6,8,9の倍数の判定法は？" },
      { number: 2, level: 1, checkPoint: "1〜nに含まれるpの倍数の個数は？" },
      { number: 3, level: 2, checkPoint: "素数とはどんな数？また、素数条件の扱いの基本ポイントは？" },
      { number: 4, level: 3, checkPoint: "素数条件の扱いとして、ab=(pの倍数)なら何が言える？" },
      { number: 5, level: 1, checkPoint: "√⚫︎が整数となるための条件は？ また、n/⚫︎が整数になるための条件は？" },
      { number: 6, level: 2, checkPoint: "n! に含まれる素因数pの個数は？" },
      { number: 7, level: 2, checkPoint: "正の約数の個数は？また、総和は？" },
      { number: 8, level: 3, checkPoint: "正の約数の個数が与えられたら、元の数をどのように文字設定する？" },
      { number: 9, level: 2, checkPoint: "最大公約数、最小公倍数についての有名な関係3つは？" },
      { number: 10, level: 3, checkPoint: "互いに素であることを示すためにはどのような証明法を用いる？" },
      { number: 11, level: 1, checkPoint: "ユークリッドの互除法を用いた最大公約数の求め方は？" },
      { number: 12, level: 3, checkPoint: "ユークリッドの互除法を用いるのはどのような最大公約数を求める時？" },
      { number: 13, level: 2, checkPoint: "倍数・余りの証明問題において、最も有名な解法とは？" },
      { number: 14, level: 2, checkPoint: "連続n整数の積は何の倍数？この性質はどのような時に用いる？" },
      { number: 15, level: 2, checkPoint: "倍数・余りの証明問題において、特にの形の問題では、どのような方針を考慮する？" },
      { number: 16, level: 4, checkPoint: "pで割った余りで分類してうまくいかない時の解法は？" },
      { number: 17, level: 1, checkPoint: "合同式とは？ また、その性質とは？" },
      { number: 18, level: 2, checkPoint: "合同式が特に活きるのは、どのような整数の剰余を考える時？" },
      { number: 19, level: 3, checkPoint: "1の位とはどのような捉え方をすれば良い？面倒な余りの場合分けで役立つのは？" },
      { number: 20, level: 4, checkPoint: "合同式の除法が成り立つのはどのような時？" },
      { number: 21, level: 1, checkPoint: "1次不定方程式の解法は？" },
      { number: 22, level: 2, checkPoint: "1次不定方程式で特殊解を見つけにくい時の方法は？" },
      { number: 23, level: 3, checkPoint: "余りバラバラの定理とその証明は？また、1次の不定方程式の解が存在することの証明は？" },
      { number: 24, level: 4, checkPoint: "ax+byの形で任意の整数が表せることの証明は？(a,bは互いに素)" },
      { number: 25, level: 2, checkPoint: "方程式の整数解を求める上での基本方針は？" },
      { number: 26, level: 2, checkPoint: "方程式の整数解を求める上で、積の形を作る以外に考えるべき方針は？" },
      { number: 27, level: 2, checkPoint: "2次方程式の整数解で値をしぼるためによく用いる不等式とは？" },
      { number: 28, level: 3, checkPoint: "2次方程式の整数解で、”積の形つくる” “判別式でしぼる” 以外の方法は？" },
      { number: 29, level: 1, checkPoint: "n進数を10進数に直す方法は？また、10進数をn進数に直す方法は？" },
      { number: 30, level: 2, checkPoint: "n進法の小数を10進数に直す方法は？また、10進数をn進法の小数に直す方法は？" },
      { number: 31, level: 2, checkPoint: "n進数がm桁である時、どんな式で評価できる？" },
      { number: 32, level: 3, checkPoint: "n進数で表した時、各桁の数に対する束縛条件は？" },
    ],
  },
  "2b-7": {
    title: "技2B 第7章（数列）",
    problems: [
      { number: 1, level: 1, checkPoint: "等差数列・等比数列の数式化はどのようにして行う？" },
      { number: 2, level: 2, checkPoint: "a,b,c の順に等差数列 ときたら…？ また、a,b,c の順に等比数列 ときたら…？" },
      { number: 3, level: 3, checkPoint: "複利とは？借金の問題は、最終的にはどのような問題に帰着される？" },
      { number: 4, level: 3, checkPoint: "既約分数の総和を求める方針は？" },
      { number: 5, level: 1, checkPoint: "Σ公式、全部言える？ k=1 がスタートでない時はどうする？" },
      { number: 6, level: 2, checkPoint: "初項からnが入るようなものであっても、一般項をきちんとn とk で表し和を求めれる？" },
      { number: 7, level: 2, checkPoint: "部分分数分解により和が求まるものなどは、Σの中身をどのような形にするのが重要？" },
      { number: 8, level: 3, checkPoint: "Σk<sup>n</sup> (n≧2)の公式の証明はどのようにする？" },
      { number: 9, level: 1, checkPoint: "和から一般項を求める方法は？また、論証上注意すべき点は？" },
      { number: 10, level: 2, checkPoint: "Σ(等差)×(等比) の和の求め方は？" },
      { number: 11, level: 3, checkPoint: "Σの中身の (2次)×(指数)を、強引にf(k+1)-f(k) の形にするアイデアにおいて、f(k)はどんな形？" },
      { number: 12, level: 3, checkPoint: "偶数項と奇数項で規則が異なる時は、どのように一般項を求める？" },
      { number: 13, level: 1, checkPoint: "階差数列の一般項の求め方は？また、論証上注意すべき点は？" },
      { number: 14, level: 3, checkPoint: "一見わかりにくい数列の規則の見つけ方は？" },
      { number: 15, level: 2, checkPoint: "群数列の解法、説明できる？" },
      { number: 16, level: 3, checkPoint: "平面上に規則的に並べられた数列は、何に対応させて考える？" },
      { number: 17, level: 1, checkPoint: "格子点の個数の求め方、説明できる？" },
      { number: 18, level: 2, checkPoint: "x＝k で切ると場合分けが面倒な時のコツの1つは？" },
      { number: 19, level: 3, checkPoint: "x=k (または y=k) で切る際に場合分けが必要なのはどのようなとき？" },
      { number: 20, level: 4, checkPoint: "空間内の格子点の個数の求め方は？" },
      { number: 21, level: 1, checkPoint: "階差型の漸化式に気づくポイントは？ また、特性方程式からのカタマリ等比形の解法は？" },
      { number: 22, level: 2, checkPoint: "a<sub>n+1</sub> = r・a<sub>n</sub> / (p・a<sub>n</sub> + q<sup>n</sup>) 型の解法は？ また、a<sub>n+1</sub> = p<sup>n</sup>・a<sub>n</sub> + q<sup>n</sup> 型の解法は？" },
      { number: 23, level: 3, checkPoint: "a<sub>n+1</sub> = p・a<sub>n</sub> + q・n + r型の解法は？ また、a<sub>n+1</sub> = p・{a<sub>n</sub>}<sup>q</sup> 型の解法は？" },
      { number: 24, level: 3, checkPoint: "階比型漸化式の解法は？ また、a<sub>n+1</sub> = p・a<sub>n</sub> + q・n<sup>2</sup> + r・n + s 型の解法は？" },
      { number: 25, level: 3, checkPoint: "分数型漸化式 (一般型) の解法は？" },
      { number: 26, level: 2, checkPoint: "和を含む漸化式の解法のポイントは？" },
      { number: 27, level: 3, checkPoint: "偶奇分けされた漸化式の解法のポイントは？" },
      { number: 28, level: 2, checkPoint: "図形列の問題では、どのような図形に着目して何をする？" },
      { number: 29, level: 2, checkPoint: "三項間漸化式の解法の流れを説明できる？" },
      { number: 30, level: 2, checkPoint: "係数対称型(サイクリック)の連立漸化式の解法は？" },
      { number: 31, level: 3, checkPoint: "係数非対称型の連立漸化式の解法は？" },
      { number: 32, level: 4, checkPoint: "漸化式は解くのが全てではない。解かずにどのような利用方法がある？" },
      { number: 33, level: 1, checkPoint: "数学的帰納法のメカニズムを説明できる？" },
      { number: 34, level: 2, checkPoint: "nがらみの数の大小関係を示すには？" },
      { number: 35, level: 3, checkPoint: "2個仮定の漸化式のメカニズムは？" },
      { number: 36, level: 3, checkPoint: "全部仮定の漸化式のメカニズムは？" },
    ],
  },
  "1a-1": {
    title: "技1A 第1章（基盤）",
    problems: [
      { number: 1, level: 1, checkPoint: "展開公式は大丈夫？工夫した展開の仕方は？" },
      { number: 2, level: 2, checkPoint: "因数分解公式は大丈夫？x<sup>3</sup>+y<sup>3</sup>+z<sup>3</sup>-3xyzの因数分解もパッと出る？" },
      { number: 3, level: 2, checkPoint: "因数分解で文字がいくつか混ざっているときの整理の仕方は？" },
      { number: 4, level: 2, checkPoint: "複2次式の因数分解でよく用いるテクニカルな変形は？また、a<sup>n</sup>-b<sup>n</sup>の因数分解は？" },
      { number: 5, level: 1, checkPoint: "√⚫︎<sup>2</sup> = ？" },
      { number: 6, level: 1, checkPoint: "二重根号の外し方は？また、”小数部分”の表し方は？" },
      { number: 7, level: 2, checkPoint: "対称式の式変形のポイントは？" },
      { number: 8, level: 2, checkPoint: "相反式の式変形のポイントは？" },
      { number: 9, level: 1, checkPoint: "複数の1次不等式を整理するためのコツは？" },
      { number: 10, level: 2, checkPoint: "絶対値を含む方程式・不等式の解法の基本は？" },
      { number: 11, level: 3, checkPoint: "文字係数入りの1次方程式・不等式を解く問題で注意することとは？" },
      { number: 12, level: 3, checkPoint: "不等式の解は何を利用して考えることができる？" },
      { number: 13, level: 1, checkPoint: "命題p→ q の真偽の調べ方は？" },
      { number: 14, level: 1, checkPoint: "逆、裏、対偶とは？元の命題と対偶の関係は？" },
      { number: 15, level: 2, checkPoint: "十分条件、必要条件とは何か、説明できる？" },
      { number: 16, level: 3, checkPoint: "2変数の不等式の必要十分条件問題で用いるテクニックは？" },
      { number: 17, level: 1, checkPoint: "証明問題における対偶法とは？どのような命題の証明で用いやすい？" },
      { number: 18, level: 2, checkPoint: "証明問題における背理法とは？どのような命題の証明で用いやすい？" },
      { number: 19, level: 3, checkPoint: "有理数・無理数の相等とは？また、その証明方法は？" },
      { number: 20, level: 4, checkPoint: "鳩ノ巣原理とそのポイントは？" },
    ],
  },
  "1a-4": {
    title: "技1A 第4章（データの分析）",
    problems: [
      { number: 1, level: 1, checkPoint: "平均値、中央値、最頻値とは？また、データが偶数個の時の中央値の取り方は？" },
      { number: 2, level: 2, checkPoint: "平均値からわかる情報とは？" },
      { number: 3, level: 1, checkPoint: "範囲とは？四分位数とは？四分位範囲とは？四分位偏差とは？" },
      { number: 4, level: 2, checkPoint: "箱ひげ図が表現しているものとは？" },
      { number: 5, level: 1, checkPoint: "分散・標準偏差、それぞれの求め方は？" },
      { number: 6, level: 2, checkPoint: "分散・標準偏差とは、どのような指標？" },
      { number: 7, level: 3, checkPoint: "分散の(定義式以外の)もう1つの計算方法とは？" },
      { number: 8, level: 3, checkPoint: "仮平均を用いた平均、分散の求め方は？" },
      { number: 9, level: 1, checkPoint: "相関係数と散布図の関係性は？" },
      { number: 10, level: 2, checkPoint: "相関係数・共分散を求める数式は？" },
      { number: 11, level: 3, checkPoint: "データの変換(X=ax+b)により、平均、分散、標準偏差、共分散、相関係数はどうなる？" },
      { number: 12, level: 3, checkPoint: "仮設検定の考え方は？対立仮説とは？帰無仮説とは？" },
    ],
  },
  "2b-1": {
    title: "技2B 第1章（式と証明）",
    problems: [
      { number: 1, level: 1, checkPoint: "√i という数は存在する？ 複素数の相等とは？" },
      { number: 2, level: 2, checkPoint: "z＝⚫︎+▲i を次数の高い式に代入するときのコツは？" },
      { number: 3, level: 3, checkPoint: "x<sup>2</sup>+x+1=0の虚数解ωについての性質3つは？" },
      { number: 4, level: 3, checkPoint: "ω<sup>n</sup> がもつ性質は？" },
      { number: 5, level: 1, checkPoint: "恒等式の扱いの2通りの方法とは？" },
      { number: 6, level: 1, checkPoint: "2文字の恒等式の扱い方は？" },
      { number: 7, level: 2, checkPoint: "2文字の2次式が1次式の積に因数分解されるにはどうなれば良い？" },
      { number: 8, level: 3, checkPoint: "整式の次数決定問題の解法は？" },
      { number: 9, level: 1, checkPoint: "x＝√⚫︎+▲を次数の高い式に代入するときのコツは？" },
      { number: 10, level: 2, checkPoint: "整式の割り算における文字設定のポイントは？" },
      { number: 11, level: 3, checkPoint: "P(x)をf(x)=(x-a)<sup>2</sup>で割った余りは、どのような工夫を用いる？" },
      { number: 12, level: 4, checkPoint: "x<sup>2</sup>+x+1 で割った余りはどのように考える？" },
      { number: 13, level: 1, checkPoint: "等式条件がある等式の証明の考え方2つは？" },
      { number: 14, level: 2, checkPoint: "比例式はどのように扱う？" },
      { number: 15, level: 3, checkPoint: "「a,b,cの少なくとも1つが⚫︎」ときたら？「a,b,cの全てが⚫︎」ときたら？" },
      { number: 16, level: 4, checkPoint: "複雑な等式条件がある等式の証明では、まず何を考えるのがよい？" },
      { number: 17, level: 1, checkPoint: "A≧Bを示すには？また、√ や 絶対値がありA-Bが簡単になりそうにないときはどうする？" },
      { number: 18, level: 1, checkPoint: "大-小≧0 を示すうえでの、式変形のコツ2つは？" },
      { number: 19, level: 2, checkPoint: "大-小≧0 を示すうえで、関数のグラフが描けそうなときの解法は？" },
      { number: 20, level: 3, checkPoint: "文字式の大小比較を解くには？" },
      { number: 21, level: 2, checkPoint: "4個の相加相乗平均の不等式の証明方法は？" },
      { number: 22, level: 2, checkPoint: "3個の相加相乗平均の不等式の証明方法は？ 2通りのやり方でいける？" },
      { number: 23, level: 3, checkPoint: "コーシーシュワルツの不等式の証明と、等号成立条件は？ また、ベクトルによる理解はできている？" },
      { number: 24, level: 4, checkPoint: "三角不等式とは？" },
    ],
  },
  "2b-8": {
    title: "技2B 第8章（確率分布と統計）",
    problems: [
      { number: 1, level: 1, checkPoint: "確率変数Xの期待値E(X)、分散V(X)、標準偏差σ(X) の定義式は？" },
      { number: 2, level: 2, checkPoint: "確率変数XをY=aX+b で変換すると、期待値、分散、標準偏差はそれぞれどうなる？" },
      { number: 3, level: 2, checkPoint: "期待値の和・差・実数倍についての性質は？また、期待値の積・分散の和についての性質はいつ成り立つ？" },
      { number: 4, level: 3, checkPoint: "二項分布B(n,p)に従う確率変数の期待値、分散、標準偏差は？" },
      { number: 5, level: 2, checkPoint: "確率密度関数とその性質とは？また、連続型確率変数の期待値、分散の公式は？" },
      { number: 6, level: 2, checkPoint: "正規分布とその性質とは？正規分布 N(m,σ<sup>2</sup>)を標準化するには？" },
      { number: 7, level: 3, checkPoint: "標準正規分布 N(0,1)を用いて確率を求めるには？" },
      { number: 8, level: 3, checkPoint: "二項分布B(n,p)に従う確率変数は、nが十分大きいと、どのような分布に従うとできる？" },
      { number: 9, level: 2, checkPoint: "母平均m, 母標準偏差σ の母集団から抽出した大きさnの標本の、標本平均と標準偏差は？" },
      { number: 10, level: 3, checkPoint: "標本の大きさn,  標本平均 X̄, 母標準偏差 σ のとき、母平均mに対する信頼度95%の信頼区間は？" },
      { number: 11, level: 3, checkPoint: "標本比率をRとしたとき、母比率pに対する信頼度95%の信頼区間は？" },
      { number: 12, level: 3, checkPoint: "仮設検定の手順は？" },
    ],
  },
};

const terms = [
  {
    id: "term1",
    title: "1学期",
    units: [
      {
        id: "term1-lecture1",
        title: "1学期第1講　技1A 第2章（最大・最小）",
        chapterRef: "1a-2",
        problemNumbers: [1, 2, 3, 4, 5, 7, 9, 10, 11, 13, 15, 17],
        homeworkNumbersSSSA: [4, 5, 7, 9, 10, 11, 13, 15, 17],
        homeworkNumbersSBCT: [2, 3, 4, 7, 9, 10, 11, 13, 15, 17],
      },
      {
        id: "term1-lecture2",
        title: "1学期第2講　技1A 第3章（方程式・不等式）",
        chapterRef: "1a-3",
        problemNumbers: [1, 2, 3, 5, 6, 8, 9, 10, 13, 15, 17, 21, 22, 25, 26],
        homeworkNumbersSSSA: [],
        homeworkNumbersSBCT: [2, 3, 6, 8, 10, 13, 15, 17, 22, 25],
      },
      {
        id: "term1-lecture3",
        title: "1学期第3講　技2B 第3章（三角関数）",
        chapterRef: "2b-3",
        problemNumbers: [1, 2, 3, 5, 7, 8, 9, 10, 11, 13, 14, 15, 17, 18, 21, 22, 23, 25, 26, 29, 30, 33, 34],
        homeworkNumbersSSSA: [8, 11, 15, 23, 25, 26, 30],
        homeworkNumbersSBCT: [3, 8, 10, 11, 15, 22, 26, 30],
      },
      {
        id: "term1-lecture4",
        title: "1学期第4講　技2B 第4章（指数・対数関数）",
        chapterRef: "2b-4",
        problemNumbers: [1, 2, 3, 5, 6, 9, 10, 11, 13, 14, 15, 17, 18, 21, 22],
        homeworkNumbersSSSA: [6, 10, 11, 15, 17, 18, 21, 22],
        homeworkNumbersSBCT: [6, 10, 11, 15, 17, 18, 21, 22],
      },
      {
        id: "term1-lecture5",
        title: "1学期第5講　技2B 第5章（微分法）",
        chapterRef: "2b-5",
        problemNumbers: [1, 2, 3, 5, 6, 7, 9, 10, 11, 13, 14, 17, 18, 19, 21, 25, 26],
        homeworkNumbersSSSA: [6, 7, 11, 19, 21, 25, 26],
        homeworkNumbersSBCT: [6, 7, 10, 11, 14, 18, 19, 21, 25, 26],
      },
      {
        id: "term1-lecture6",
        title: "1学期第6講　技2B 第6章（積分法）",
        chapterRef: "2b-6",
        problemNumbers: [1, 2, 5, 6, 9, 10, 11, 13, 14, 17, 18],
        homeworkNumbersSSSA: [2, 5, 6, 11, 17, 18],
        homeworkNumbersSBCT: [2, 5, 6, 10, 17, 18],
      },
      {
        id: "term1-lecture7",
        title: "1学期第7講　技1A 第5章（三角比・図形）",
        chapterRef: "1a-5",
        problemNumbers: [1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 13, 14, 15, 17, 18, 21, 22, 25, 26, 30],
        referenceNumbers: [30],
        homeworkNumbersSSSA: [2, 6, 7, 9, 10, 11, 14, 15, 18, 26],
        homeworkNumbersSBCT: [1, 2, 3, 5, 10, 11, 15, 18, 26],
      },
      {
        id: "term1-lecture8",
        title: "1学期第8講　技2B 第2章（図形と式①）",
        chapterRef: "2b-2",
        problemNumbers: [1, 2, 3, 5, 7, 9, 10, 11, 13, 14, 15, 17, 18, 21],
        homeworkNumbersSSSA: [5, 7, 10, 11, 14, 17, 18, 21],
        homeworkNumbersSBCT: [5, 7, 10, 11, 13, 17, 18, 21],
      },
      {
        id: "term1-lecture9",
        title: "1学期第9講　技2B 第2章（図形と式②）",
        chapterRef: "2b-2",
        problemNumbers: [25, 26, 27, 29, 30, 33, 34, 37, 38, 41, 42],
        homeworkNumbersSSSA: [25, 26, 27, 29, 30, 33, 38, 41, 42],
        homeworkNumbersSBCT: [25, 26, 27, 29, 30, 33, 38, 41, 42],
      },
      {
        id: "term1-lecture10",
        title: "1学期第10講　技2B 第9章（平面ベクトル）",
        chapterRef: "2b-9",
        problemNumbers: [1, 3, 4, 5, 6, 9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 21, 22, 25, 29],
        homeworkNumbersSSSA: [4, 6, 10, 12, 15, 19, 21, 22, 25, 29],
        homeworkNumbersSBCT: [1, 4, 6, 10, 11, 12, 15, 19, 21, 22, 25],
      },
      {
        id: "term1-lecture11",
        title: "1学期第11講　技2B 第9章（空間ベクトル）",
        chapterRef: "2b-9",
        problemNumbers: [33, 34, 37, 38, 39, 41, 42, 43, 45, 46, 49, 50, 53, 54, 57, 58],
        homeworkNumbersSSSA: [39, 43, 46, 50, 53, 54, 57, 58],
        homeworkNumbersSBCT: [37, 38, 39, 43, 46, 50, 53, 54, 57, 58],
      },
      {
        id: "term1-lecture12",
        title: "1学期第12講　技1A 第6章（場合の数）",
        chapterRef: "1a-6",
        problemNumbers: [1, 2, 5, 6, 7, 8, 9, 11, 13, 14, 15, 17, 18, 19, 21, 22, 23, 25, 27, 29, 30, 32, 33, 34, 37],
        homeworkNumbersSSSA: [2, 9, 11, 14, 15, 18, 19, 22, 23, 25, 27, 29, 32],
        homeworkNumbersSBCT: [2, 9, 11, 14, 15, 18, 19, 22, 23, 25, 27, 29, 32],
      },
      {
        id: "term1-lecture13",
        title: "1学期第13講　技1A 第7章（確率）",
        chapterRef: "1a-7",
        problemNumbers: [1, 3, 4, 5, 6, 9, 10, 11, 13, 14, 17, 18, 21, 22, 25, 26, 29, 30],
        homeworkNumbersSSSA: [3, 6, 11, 13, 14, 17, 18, 22, 25, 26],
        homeworkNumbersSBCT: [3, 6, 10, 11, 13, 14, 17, 18, 22, 25, 26],
      },
      {
        id: "term1-lecture14",
        title: "1学期第14講　技1A 第8章（整数①）",
        chapterRef: "1a-8",
        problemNumbers: [1, 2, 3, 5, 6, 7, 9, 11, 13, 14, 15, 17, 18],
        homeworkNumbersSSSA: [3, 5, 6, 7, 9, 11, 13, 14, 15, 17, 18],
        homeworkNumbersSBCT: [1, 2, 5, 6, 7, 9, 11, 13, 14, 17, 18],
      },
      {
        id: "term1-lecture15",
        title: "1学期第15講　技1A 第8章（整数②）",
        chapterRef: "1a-8",
        problemNumbers: [21, 22, 25, 26, 27, 29, 30, 31],
        homeworkNumbersSSSA: [21, 22, 25, 26, 27, 29, 30, 31],
        homeworkNumbersSBCT: [21, 22, 25, 26, 27, 29, 30, 31],
      },
      {
        id: "term1-lecture17",
        title: "1学期第17講　技2B 第7章（数列①）",
        chapterRef: "2b-7",
        problemNumbers: [1, 2, 5, 6, 7, 9, 10, 13, 15, 17, 18],
        homeworkNumbersSSSA: [],
        homeworkNumbersSBCT: [],
      },
      {
        id: "term1-lecture18",
        title: "1学期第18講　技2B 第7章（数列②）",
        chapterRef: "2b-7",
        problemNumbers: [21, 22, 26, 28, 29, 30, 33, 34],
        homeworkNumbersSSSA: [],
        homeworkNumbersSBCT: [],
      },
    ],
  },
  {
    id: "term2",
    title: "2学期",
    units: [
      {
        id: "term2-lecture1",
        title: "2学期第1講　技1A 第1章（基盤）",
        chapterRef: "1a-1",
        problemNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
        referenceNumbers: [20],
        homeworkNumbersSSSA: [2, 3, 4, 7, 15, 16, 17, 18, 19],
        homeworkNumbersSBCT: [2, 3, 4, 6, 7, 8, 15, 16, 17, 18, 19],
      },
      {
        id: "term2-lecture1-2b1",
        title: "2学期第1講　技2B 第1章（式と証明）",
        chapterRef: "2b-1",
        problemNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
        referenceNumbers: [12, 16, 24],
        homeworkNumbersSSSA: [8, 10, 11, 18, 22, 23],
        homeworkNumbersSBCT: [8, 10, 11, 18, 22, 23],
      },
      {
        id: "term2-lecture2",
        title: "2学期第2講　技1A 第2章（最大・最小）",
        chapterRef: "1a-2",
        problemNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18, 19],
        homeworkNumbersSSSA: [6, 8, 10, 12, 14, 18, 19],
        homeworkNumbersSBCT: [5, 6, 8, 10, 13, 15, 17, 18],
      },
      {
        id: "term2-lecture3",
        title: "2学期第3講　技1A 第3章（方程式・不等式）",
        chapterRef: "1a-3",
        problemNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23, 25, 26, 27, 28],
        homeworkNumbersSSSA: [2, 4, 7, 16, 18, 19, 27, 28],
        homeworkNumbersSBCT: [2, 3, 7, 8, 10, 14, 16, 18, 26, 27],
      },
      {
        id: "term2-lecture4-2b3",
        title: "2学期第4講　技2B 第3章（三角関数）",
        chapterRef: "2b-3",
        problemNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 25, 26, 27, 28, 29, 30, 31, 33, 34],
        homeworkNumbersSSSA: [4, 8, 12, 16, 23, 27, 34],
        homeworkNumbersSBCT: [8, 12, 15, 23, 26, 34],
      },
      {
        id: "term2-lecture4-2b4",
        title: "2学期第4講　技2B 第4章（指数・対数関数）",
        chapterRef: "2b-4",
        problemNumbers: [1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22],
        homeworkNumbersSSSA: [7, 10, 12, 16, 19],
        homeworkNumbersSBCT: [7, 10, 12, 16, 19],
      },
      {
        id: "term2-lecture5",
        title: "2学期第5講　技2B 第5章（微分法）",
        chapterRef: "2b-5",
        problemNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 20, 21, 22, 23, 25, 26, 27],
        homeworkNumbersSSSA: [6, 8, 12, 15, 20, 22, 23, 27],
        homeworkNumbersSBCT: [6, 11, 12, 15, 20, 21, 23, 26, 27],
      },
      {
        id: "term2-lecture6",
        title: "2学期第6講　技2B 第6章（積分法）",
        chapterRef: "2b-6",
        problemNumbers: [1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        homeworkNumbersSSSA: [3, 4, 7, 12, 16, 19],
        homeworkNumbersSBCT: [3, 4, 5, 6, 11, 12, 15],
      },
      {
        id: "term2-lecture7",
        title: "2学期第7講　技1A 第5章（三角比・図形）",
        chapterRef: "1a-5",
        problemNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
        referenceNumbers: [20, 24, 28, 32],
        homeworkNumbersSSSA: [8, 11, 16, 19, 26, 27, 30, 31],
        homeworkNumbersSBCT: [7, 11, 16, 18, 26, 27, 30, 31],
      },
      {
        id: "term2-lecture8",
        title: "2学期第8講　技2B 第2章（図形と式）",
        chapterRef: "2b-2",
        problemNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
        homeworkNumbersSSSA: [6, 12, 16, 19, 22, 23, 28, 31, 39, 41],
        homeworkNumbersSBCT: [6, 12, 16, 18, 19, 21, 22, 23, 28, 31, 37, 39, 41],
      },
      {
        id: "term2-lecture9",
        title: "2学期第9講　技2B 第9章（平面ベクトル）",
        chapterRef: "2b-9",
        problemNumbers: [1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 25, 26, 27, 29, 30, 31],
        homeworkNumbersSSSA: [2, 7, 12, 16, 19, 20, 21, 23, 26, 27, 31],
        homeworkNumbersSBCT: [2, 4, 12, 16, 19, 20, 22, 26, 27, 31],
      },
      {
        id: "term2-lecture10",
        title: "2学期第10講　技2B 第9章（空間ベクトル）",
        chapterRef: "2b-9",
        problemNumbers: [33, 34, 35, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 49, 50, 51, 52, 53, 54, 55, 57, 58, 59],
        homeworkNumbersSSSA: [40, 46, 51, 52, 54, 58],
        homeworkNumbersSBCT: [40, 46, 51, 52, 54, 58],
      },
      {
        id: "term2-lecture11",
        title: "2学期第11講　技1A 第6章（場合の数）",
        chapterRef: "1a-6",
        problemNumbers: [1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 29, 30, 31, 32, 33, 34, 35, 37, 38, 39],
        homeworkNumbersSSSA: [3, 16, 24, 26, 30, 31, 34, 38, 39],
        homeworkNumbersSBCT: [3, 9, 11, 14, 18, 24, 26, 30, 31, 34, 37, 39],
      },
      {
        id: "term2-lecture12",
        title: "2学期第12講　技1A 第7章（確率）",
        chapterRef: "1a-7",
        problemNumbers: [1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 20, 21, 22, 23, 25, 26, 27, 29, 30, 32],
        homeworkNumbersSSSA: [2, 7, 12, 15, 26, 27, 30, 32],
        homeworkNumbersSBCT: [2, 7, 11, 12, 15, 17, 19, 26, 29, 30],
      },
      {
        id: "term2-lecture13",
        title: "2学期第13講　技2B 第7章（数列）",
        chapterRef: "2b-7",
        problemNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36],
        homeworkNumbersSSSA: [3, 11, 12, 18, 24, 26, 30, 35, 36],
        homeworkNumbersSBCT: [3, 7, 11, 18, 23, 26, 30, 35, 36],
      },
      {
        id: "term2-lecture14",
        title: "2学期第14講　技1A 第8章（整数）",
        chapterRef: "1a-8",
        problemNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
        homeworkNumbersSSSA: [3, 4, 6, 12, 13, 14, 19, 22, 23, 25, 26, 27, 28, 32],
        homeworkNumbersSBCT: [3, 4, 6, 12, 13, 14, 22, 25, 26, 27, 28, 30, 32],
      },
      {
        id: "term2-lecture16",
        title: "2学期第16講　技1A 第4章（データの分析）",
        chapterRef: "1a-4",
        problemNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        homeworkNumbersSSSA: [],
        homeworkNumbersSBCT: [],
      },
    ],
  },
  {
    id: "term3",
    title: "3学期以降",
    units: [
      {
        id: "term3-lecture1",
        title: "3学期第1講　技1A 第2章（最大・最小）",
        chapterRef: "1a-2",
        problemNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
        homeworkNumbersSSSA: [8, 12, 14, 16, 18, 19, 20],
        homeworkNumbersSBCT: [6, 7, 8, 10, 11, 14, 18, 19],
      },
      {
        id: "term3-lecture2",
        title: "3学期第2講　技1A 第3章（方程式・不等式）",
        chapterRef: "1a-3",
        problemNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28],
        homeworkNumbersSSSA: [7, 12, 16, 20, 27, 28],
        homeworkNumbersSBCT: [8, 11, 12, 14, 16, 19, 27, 28],
      },
      {
        id: "term3-lecture3-2b3",
        title: "3学期第3講　技2B 第3章（三角関数）",
        chapterRef: "2b-3",
        problemNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36],
        homeworkNumbersSSSA: [6, 8, 18, 23, 24, 28, 31, 32],
        homeworkNumbersSBCT: [8, 18, 23, 26, 27, 31, 34],
      },
      {
        id: "term3-lecture3-2b4",
        title: "3学期第3講　技2B 第4章（指数・対数関数）",
        chapterRef: "2b-4",
        problemNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
        homeworkNumbersSSSA: [7, 12, 16, 19, 22],
        homeworkNumbersSBCT: [7, 11, 15, 19, 22],
      },
      {
        id: "term3-lecture4-2b5",
        title: "3学期第4講　技2B 第5章（微分法）",
        chapterRef: "2b-5",
        problemNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28],
        homeworkNumbersSSSA: [7, 12, 14, 23, 27, 28],
        homeworkNumbersSBCT: [3, 8, 16, 20],
      },
      {
        id: "term3-lecture4-2b6",
        title: "3学期第4講　技2B 第6章（積分法）",
        chapterRef: "2b-6",
        problemNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
        homeworkNumbersSSSA: [3, 8, 16, 20],
        homeworkNumbersSBCT: [3, 7, 15, 16, 20],
      },
      {
        id: "term3-lecture5",
        title: "3学期第5講　技2B 第2章（図形と式）",
        chapterRef: "2b-2",
        problemNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
        homeworkNumbersSSSA: [19, 20, 22, 24, 32, 39, 43, 44],
        homeworkNumbersSBCT: [6, 12, 19, 22, 23, 31, 39, 43],
      },
      {
        id: "term3-lecture6",
        title: "3学期第6講　技2B 第9章（ベクトル）",
        chapterRef: "2b-9",
        problemNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
        homeworkNumbersSSSA: [20, 24, 26, 27, 31, 32, 40, 51, 52, 56, 59, 60],
        homeworkNumbersSBCT: [19, 20, 22, 25, 26, 27, 30, 31, 40, 51, 52, 55, 59],
      },
      {
        id: "term3-lecture7",
        title: "3学期第7講　技1A 第6章（場合の数）",
        chapterRef: "1a-6",
        problemNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
        homeworkNumbersSSSA: [4, 16, 22, 28, 36, 39],
        homeworkNumbersSBCT: [16, 22, 24, 27, 35, 39],
      },
      {
        id: "term3-lecture7-1a7",
        title: "3学期第7講　技1A 第7章（確率）",
        chapterRef: "1a-7",
        problemNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
        homeworkNumbersSSSA: [7, 16, 20, 27, 31],
        homeworkNumbersSBCT: [2, 7, 12, 20, 26, 30, 32],
      },
      {
        id: "term3-lecture8",
        title: "3学期第8講　技2B 第7章（数列）",
        chapterRef: "2b-7",
        problemNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36],
        homeworkNumbersSSSA: [8, 12, 14, 26, 27, 31, 35, 36],
        homeworkNumbersSBCT: [8, 12, 14, 24, 27, 31, 35, 36],
      },
      {
        id: "term3-lecture9",
        title: "3学期第9講　技1A 第8章（整数）",
        chapterRef: "1a-8",
        problemNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
        homeworkNumbersSSSA: [8, 16, 23, 24, 28, 32],
        homeworkNumbersSBCT: [8, 14, 23, 28, 32],
      },
      {
        id: "term3-lecture11",
        title: "3学期第11講　技2B 第8章（確率分布と統計）",
        chapterRef: "2b-8",
        problemNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        homeworkNumbersSSSA: [],
        homeworkNumbersSBCT: [],
      },
    ],
  },
];
