// 技の問題データを2階層で管理する
// 1. problemBank: 技の問題そのもの（章ごとに1回だけ定義。番号・レベル・Check Point文）
// 2. terms: 学期ごとの講の割り当て（問題バンクを参照し、講ごとの宿題必須番号だけを持つ）

const problemBank = {
  "1a-2": {
    title: "技1A 第2章（最大・最小）",
    problems: [
      { number: 1, level: 1, checkPoint: "平行移動、対称移動の公式は？" },
      { number: 2, level: 1, checkPoint: "絶対値入り関数のグラフの書き方は？" },
      { number: 3, level: 2, checkPoint: "場合分けが必要な式・グラフの特徴は？" },
      { number: 4, level: 2, checkPoint: "式処理のポイント３つは？Maxminで文字を置換したときの注意点は？" },
      { number: 5, level: 2, checkPoint: "グラフを描いた後、何に注意して場合分けする？" },
      { number: 7, level: 2, checkPoint: "１変数関数の最大最小の求め方３つは？" },
      { number: 9, level: 2, checkPoint: "簡単な等式条件がある２変数関数のMaxminの求め方と注意点は？" },
      { number: 10, level: 2, checkPoint: "２変数関数で=kとおいてMaxmin求めるのはどんな時？" },
      { number: 11, level: 2, checkPoint: "対称式の扱いのポイントと、注意点は？" },
      { number: 13, level: 2, checkPoint: "予選決勝法の使える場面と、その方法は？" },
      { number: 15, level: 2, checkPoint: "２変数関数のMaxminで用いる有名不等式とは？" },
      { number: 17, level: 2, checkPoint: "３変数関数のMaxminの解法とは？" },
    ],
  },
  "1a-3": {
    title: "技1A 第3章（方程式・不等式）",
    problems: [
      { number: 1, level: 1, checkPoint: "2次方程式の解の個数の求め方は？" },
      { number: 2, level: 2, checkPoint: "方程式の共通解のときたら、解法は？ また、連立方程式とみて、最後に確認すべきことは？" },
      { number: 3, level: 2, checkPoint: "実数係数の方程式が虚数解をもつときの扱いは？" },
      { number: 5, level: 1, checkPoint: "解の差・解の比など、特殊な解の条件が与えられたら？" },
      { number: 6, level: 2, checkPoint: "α , βを2解にもつ2次方程式の作り方は？" },
      { number: 8, level: 2, checkPoint: "3次方程式における解と係数の関係は？" },
      { number: 9, level: 1, checkPoint: "対称式からなる連立方程式の解き方は？" },
      { number: 10, level: 2, checkPoint: "対称式からなる連立方程式の解き方は？" },
      { number: 13, level: 1, checkPoint: "方程式でまず最初に確認すべきことは？" },
      { number: 15, level: 2, checkPoint: "2次方程式の解の配置(範囲つき解の個数)は何に注目して立式する？" },
      { number: 17, level: 2, checkPoint: "方程式で置換した時に忘れずすべきことは？また、解の対応関係の調べ方は？" },
      { number: 21, level: 1, checkPoint: "不等式の解はグラフでどのように扱える？" },
      { number: 22, level: 2, checkPoint: "不等式でまず最初に確認すべきことは？" },
      { number: 25, level: 2, checkPoint: "「すべてのxでf(x)>a」 ときたら…？" },
      { number: 26, level: 2, checkPoint: "「あるxでf(x)>a」 ときたら…？" },
    ],
  },
  "2b-3": {
    title: "技2B 第3章（三角関数）",
    problems: [
      { number: 1, level: 1, checkPoint: "三角関数の値の定義は？" },
      { number: 2, level: 1, checkPoint: "cos(θ+π)=？、sin(θ+π/2)=？、cos(-θ)=？などすぐに言える？" },
      { number: 3, level: 2, checkPoint: "三角関数のグラフの描き方、周期の求め方は？" },
      { number: 5, level: 1, checkPoint: "三角関数の相互関係とは？" },
      { number: 7, level: 1, checkPoint: "sin, cos の対称式の扱いは？" },
      { number: 8, level: 2, checkPoint: "t=sinx+cosxと置換した後にやるべきこと2つは？" },
      { number: 9, level: 1, checkPoint: "1つのsinにまとまった三角方程式の解き方は？" },
      { number: 10, level: 2, checkPoint: "種類が1つにまとまった三角方程式の解き方は？" },
      { number: 11, level: 1, checkPoint: "方程式でまず考慮すべき方針は？" },
      { number: 13, level: 1, checkPoint: "加法定理、ちゃんと覚えている？" },
      { number: 14, level: 2, checkPoint: "加法定理、ちゃんと覚えている？" },
      { number: 15, level: 2, checkPoint: "2直線のなす角を求める公式とその作り方は？" },
      { number: 17, level: 1, checkPoint: "2倍角、3倍角、半角、全部言える？" },
      { number: 18, level: 2, checkPoint: "cos36°の求め方、知ってる？" },
      { number: 21, level: 1, checkPoint: "sinとcos の1次式の和・差はどう扱う？" },
      { number: 22, level: 2, checkPoint: "sinとcos の1次式の和・差はどう扱う？" },
      { number: 25, level: 1, checkPoint: "和積公式、積和公式、作れる？" },
      { number: 26, level: 2, checkPoint: "和積公式はどのような場面で活躍する？" },
      { number: 29, level: 2, checkPoint: "方程式の解の個数はどのように考える？" },
      { number: 30, level: 2, checkPoint: "方程式で置換したら…何を考える？" },
      { number: 33, level: 2, checkPoint: "仰角、俯角の意味は？" },
      { number: 34, level: 2, checkPoint: "図形量の最大値を求めるためには？" },
    ],
  },
  "2b-4": {
    title: "技2B 第4章（指数・対数関数）",
    problems: [
      { number: 1, level: 1, checkPoint: "指数法則は大丈夫？" },
      { number: 2, level: 1, checkPoint: "対数法則は大丈夫？" },
      { number: 3, level: 2, checkPoint: "ax=by の形で、底が揃いにくいような式の扱いは？" },
      { number: 5, level: 1, checkPoint: "y=axのグラフ、y=logaxのグラフの概形は？" },
      { number: 6, level: 2, checkPoint: "指数対数の大小比較のコツは？" },
      { number: 9, level: 1, checkPoint: "対数の式処理のポイントは？" },
      { number: 10, level: 2, checkPoint: "指数の相反式の扱い方は？" },
      { number: 11, level: 2, checkPoint: "２変数関数の最大最小で最優先したい発想とは？" },
      { number: 13, level: 1, checkPoint: "指数の式処理のポイントは？" },
      { number: 14, level: 1, checkPoint: "対数の不等式で、真数の比較をする上で注意すべき点は？" },
      { number: 15, level: 2, checkPoint: "対数の不等式で、底に文字定数を含む場合に注意すべき点は？" },
      { number: 17, level: 2, checkPoint: "不等式の成立条件ときたら？対数の不等式で底に文字定数を含む場合に注意すべき点は？" },
      { number: 18, level: 2, checkPoint: "方程式の解の個数ときたら？ 本問で真数条件を一部無視できる理由は？" },
      { number: 21, level: 2, checkPoint: "桁数の求め方は？" },
      { number: 22, level: 2, checkPoint: "小数第⚫︎位に初めて現れる数の求め方は？" },
    ],
  },
  "2b-5": {
    title: "技2B 第5章（微分法）",
    problems: [
      { number: 1, level: 1, checkPoint: "平均変化率とは？微分係数の定義は？" },
      { number: 2, level: 2, checkPoint: "微分係数の定義は？ 微分係数の定義を利用した極限値の計算上のポイントは？" },
      { number: 3, level: 1, checkPoint: "導関数の定義は？" },
      { number: 5, level: 1, checkPoint: "接線と曲線のもう１つの交点を求める際の計算上のポイントは？" },
      { number: 6, level: 2, checkPoint: "共通接線（接点異なる）の立式は？" },
      { number: 7, level: 2, checkPoint: "共通接線（接点同じ）の立式は？" },
      { number: 9, level: 1, checkPoint: "面倒な極値計算のやり方は？" },
      { number: 10, level: 2, checkPoint: "3次関数が極値もつための条件は？" },
      { number: 11, level: 2, checkPoint: "「y=f(x)がx=aで極値もつ」の数式化と、立式の際の注意点は？" },
      { number: 13, level: 1, checkPoint: "２変数関数の最大最小でまず考えることは？" },
      { number: 14, level: 2, checkPoint: "文字定数含む3次関数のMaxmin求める際の場合分けのポイントは？" },
      { number: 17, level: 2, checkPoint: "3次方程式の解の個数でまず考えることは？" },
      { number: 18, level: 1, checkPoint: "3次方程式の解の個数で因数分解の次に考えることは？" },
      { number: 19, level: 2, checkPoint: "3次方程式の解の個数でx軸相手に比べる際の立式の仕方は？" },
      { number: 21, level: 2, checkPoint: "接線の本数問題の立式の仕方は？" },
      { number: 25, level: 1, checkPoint: "3次不等式を解くには？" },
      { number: 26, level: 2, checkPoint: "不等式の証明の基本的な考え方は？" },
    ],
  },
  "2b-6": {
    title: "技2B 第6章（積分法）",
    problems: [
      { number: 1, level: 1, checkPoint: "定積分における、偶関数・奇関数の性質とは？" },
      { number: 2, level: 2, checkPoint: "カタマリ積分とはどんな公式？また、1/6公式とはどんな公式？" },
      { number: 5, level: 1, checkPoint: "積分方程式（区間が変数）の解法は？" },
      { number: 6, level: 2, checkPoint: "積分方程式（区間が定数）の解法は？" },
      { number: 9, level: 1, checkPoint: "面積を求める立式の仕方は？" },
      { number: 10, level: 1, checkPoint: "1/6公式が使える面積の形 のパターンは？（全部で3パターン）" },
      { number: 11, level: 2, checkPoint: "1/6公式が使える面積の形 のパターンは？（全部で3パターン）" },
      { number: 13, level: 1, checkPoint: "カタマリ積分が使える面積の形 のパターンは？" },
      { number: 14, level: 2, checkPoint: "円がらみの面積を求める方法は？" },
      { number: 17, level: 2, checkPoint: "面積を立式する上で計算を楽にするためのポイントとは？" },
      { number: 18, level: 2, checkPoint: "放物線と直線で囲まれた面積の最小値はどのような方針で求める？" },
    ],
  },
  "1a-5": {
    title: "技1A 第5章（三角比・図形）",
    problems: [
      { number: 1, level: 1, checkPoint: "正弦定理の有名な使い所は？" },
      { number: 2, level: 2, checkPoint: "三角形の内角のsinの比が与えられた時は？" },
      { number: 3, level: 1, checkPoint: "余弦定理の有名な使い所は？" },
      { number: 4, level: 2, checkPoint: "三角形の形状決定の定石は？" },
      { number: 5, level: 1, checkPoint: "三角形の内接円の半径を求めるには？" },
      { number: 6, level: 2, checkPoint: "角の二等分線の長さ、垂線の長さの立式は？" },
      { number: 7, level: 2, checkPoint: "ヘロンの公式とは？" },
      { number: 9, level: 1, checkPoint: "角の二等分線の性質とは？" },
      { number: 10, level: 2, checkPoint: "三角形の成立条件とは？また、鋭角・鈍角三角形の成立条件は？" },
      { number: 11, level: 2, checkPoint: "チェバの定理、メネラウスの定理とは？" },
      { number: 13, level: 1, checkPoint: "円周角の定理とは？（中心角の関係含め）" },
      { number: 14, level: 2, checkPoint: "方べきの定理とは？またその本質は？" },
      { number: 15, level: 2, checkPoint: "接弦定理とは？" },
      { number: 17, level: 1, checkPoint: "円に内接する四角形の性質とは？" },
      { number: 18, level: 2, checkPoint: "円に内接する四角形の対角線の長さを求めるには？" },
      { number: 21, level: 2, checkPoint: "重心の性質は？" },
      { number: 22, level: 2, checkPoint: "正三角形についての重要な五心の性質は？" },
      { number: 25, level: 1, checkPoint: "断面の取り方で重要なテクニックは？" },
      { number: 26, level: 2, checkPoint: "四面体の内接球の半径の求め方は？ (相似を使う解法でもできる？)" },
    ],
  },
  "2b-2": {
    title: "技2B 第2章（図形と式）",
    problems: [
      { number: 1, level: 1, checkPoint: "内分点、外分点の座標の公式は？" },
      { number: 2, level: 1, checkPoint: "重心の座標の公式は？" },
      { number: 3, level: 2, checkPoint: "平行四辺形となるための条件は？ (参考：ベクトルでもできる？)" },
      { number: 5, level: 1, checkPoint: "不動点(常に通る定点)の求め方は？" },
      { number: 7, level: 2, checkPoint: "直線の平行条件、垂直条件は？ (一般形でも覚えてる？)" },
      { number: 9, level: 1, checkPoint: "点と直線の距離公式は？" },
      { number: 10, level: 2, checkPoint: "三角形の面積公式、座標verは？" },
      { number: 11, level: 2, checkPoint: "直線の対称点の求め方は？折れ線の長さの最小値を求める方法は？" },
      { number: 13, level: 1, checkPoint: "円の方程式の標準形、一般形とは？" },
      { number: 14, level: 2, checkPoint: "円を対称移動した円を求める方針は？" },
      { number: 15, level: 1, checkPoint: "円と直線の関係の数式化はどうする？" },
      { number: 17, level: 1, checkPoint: "円の接線の方程式は？" },
      { number: 18, level: 2, checkPoint: "円の接線を求める方法は？" },
      { number: 21, level: 2, checkPoint: "円と円の位置関係、整理できている？" },
      { number: 25, level: 2, checkPoint: "軌跡の幾何的解法とは？また、どういう時に使える考え方？" },
      { number: 26, level: 2, checkPoint: "軌跡の代数的解法の流れは？" },
      { number: 27, level: 2, checkPoint: "軌跡の代数的解法において、別の動点に文字おいた時の扱いは？" },
      { number: 29, level: 2, checkPoint: "軌跡を求める上で最後に注意すべきことは？" },
      { number: 30, level: 2, checkPoint: "点(s+t , st)の存在範囲の求め方と注意点は？" },
      { number: 33, level: 1, checkPoint: "正領域・負領域を用いて領域図示するコツは？" },
      { number: 34, level: 2, checkPoint: "グラフを描く上で、これがある場合は利用すると楽になる。何？" },
      { number: 37, level: 2, checkPoint: "領域内の最大最小問題の解法は？" },
      { number: 38, level: 2, checkPoint: "領域内の最大最小問題の解法は？（文章題もきちんと数式化できる？）" },
      { number: 41, level: 2, checkPoint: "直線の通過領域の問題の解法とは？" },
      { number: 42, level: 2, checkPoint: "図形の通過領域の問題の解法とは？" },
    ],
  },
  "2b-9": {
    title: "技2B 第9章（ベクトル）",
    problems: [
      { number: 1, level: 1, checkPoint: "ベクトルの加法、減法の公式とその意義は？" },
      { number: 3, level: 1, checkPoint: "内分点の公式、外分点の公式、OK？" },
      { number: 4, level: 2, checkPoint: "内分点から点の位置を求める有名変形、OK？" },
      { number: 5, level: 1, checkPoint: "絶対値の処理の仕方は？なす角の数式化は？" },
      { number: 6, level: 2, checkPoint: "絶対値の処理の仕方は？" },
      { number: 9, level: 1, checkPoint: "成分公式（大きさ、内積など）、大丈夫？" },
      { number: 10, level: 2, checkPoint: "なす角・垂直の数式化は？" },
      { number: 11, level: 2, checkPoint: "平行条件の数式化は？" },
      { number: 12, level: 2, checkPoint: "三角形の面積公式（ベクトル・成分）OK？" },
      { number: 13, level: 1, checkPoint: "直線のベクトル方程式とは？" },
      { number: 14, level: 2, checkPoint: "直線上の数式化とは？" },
      { number: 15, level: 2, checkPoint: "法線ベクトルを利用した直線の数式化とは？" },
      { number: 17, level: 2, checkPoint: "位置ベクトルの基本的発想は？(本問のようにうまく処理することもあると理解しておく)" },
      { number: 18, level: 2, checkPoint: "同一直線上にあることを示すには？" },
      { number: 19, level: 2, checkPoint: "2直線の交点の位置ベクトルの求め方は？幾何的な別解でも解ける？" },
      { number: 21, level: 1, checkPoint: "円のベクトル方程式とは？" },
      { number: 22, level: 2, checkPoint: "外接円上にある点の数式化の方法は？" },
      { number: 25, level: 2, checkPoint: "内心の位置ベクトルの求め方２通りは？" },
      { number: 29, level: 2, checkPoint: "点の存在範囲の求め方は？（わかりやすい考え方は？）" },
      { number: 33, level: 1, checkPoint: "空間座標　まずは綺麗に図を描ける？" },
      { number: 34, level: 2, checkPoint: "空間座標における2点間距離公式は？" },
      { number: 37, level: 1, checkPoint: "空間座標における内積の公式は？" },
      { number: 38, level: 2, checkPoint: "なす角の数式化と来たら？" },
      { number: 39, level: 2, checkPoint: "(空間座標における)三角形の面積公式は？" },
      { number: 41, level: 1, checkPoint: "空間座標における直線の方程式とは？" },
      { number: 42, level: 1, checkPoint: "空間座標における直線の方程式とは？" },
      { number: 43, level: 2, checkPoint: "空間座標における直線と平面の交点はどう求める？" },
      { number: 45, level: 1, checkPoint: "空間座標における球面の方程式とは？" },
      { number: 46, level: 2, checkPoint: "球面のベクトル方程式とは？" },
      { number: 49, level: 1, checkPoint: "空間座標における平面の方程式と、その求め方2通りとは？" },
      { number: 50, level: 2, checkPoint: "空間座標における直線と平面の交点はどう求める？" },
      { number: 53, level: 2, checkPoint: "空間ベクトルにおける基準ベクトルとは？交点はどのように求める？" },
      { number: 54, level: 2, checkPoint: "直線と平面の交点はどう求める？" },
      { number: 57, level: 2, checkPoint: "垂線の足の数式化、どうする？" },
      { number: 58, level: 2, checkPoint: "平面と垂直なベクトルはどのように数式化する？" },
    ],
  },
  "1a-6": {
    title: "技1A 第6章（場合の数）",
    problems: [
      { number: 1, level: 1, checkPoint: "複数の集合を整理するには？ド・モルガンの法則とは？" },
      { number: 2, level: 2, checkPoint: "複数の集合を整理するには？倍数の個数の求め方は？(詳しくは整数)" },
      { number: 5, level: 2, checkPoint: "樹形図を書く上でのポイントは？" },
      { number: 6, level: 2, checkPoint: "2種類の要素で定まるものを書き出す時のコツは？" },
      { number: 7, level: 2, checkPoint: "積が偶数となる場合の数はどう求めるのが楽？" },
      { number: 8, level: 2, checkPoint: "場合を分けて数える時のポイントは？" },
      { number: 9, level: 2, checkPoint: "隣り合う、隣り合わない　順列の求め方は？" },
      { number: 11, level: 2, checkPoint: "重複順列とは？その求め方は？" },
      { number: 13, level: 1, checkPoint: "選び方の総数はどう求める？nCr=？" },
      { number: 14, level: 2, checkPoint: "三角形の個数を求める上でのコツは？" },
      { number: 15, level: 2, checkPoint: "要素をグループ分けして求める考え方、できる？" },
      { number: 17, level: 1, checkPoint: "同じものを含む順列の場合分け、どうする？" },
      { number: 18, level: 2, checkPoint: "「この順で並ぶ」の数え方は？" },
      { number: 19, level: 2, checkPoint: "最短経路の問題の数え方は？場合分けの方法は？" },
      { number: 21, level: 1, checkPoint: "円順列、じゅず順列の考え方は？" },
      { number: 22, level: 2, checkPoint: "立方体の色塗りの考え方は？”固定する”ってどういうこと？" },
      { number: 23, level: 2, checkPoint: "同じものを含む円順列、どのように考える？" },
      { number: 25, level: 1, checkPoint: "重複組合せとは？" },
      { number: 27, level: 2, checkPoint: "整数解の個数の求め方は？" },
      { number: 29, level: 1, checkPoint: "分配の問題の4つパターンとは？" },
      { number: 30, level: 2, checkPoint: "区別あるものを区別ある組に分ける時、組の人数がわからない場合はどうする？" },
      { number: 32, level: 2, checkPoint: "区別ないものを分けるにはどうする？" },
      { number: 33, level: 1, checkPoint: "二項定理の一般項は？(詳しくは2学期)" },
      { number: 34, level: 2, checkPoint: "多項定理の一般項は？(詳しくは2学期)" },
      { number: 37, level: 2, checkPoint: "場合の数で漸化式立てる上でのポイントは？(詳しくは2学期)" },
    ],
  },
  "1a-7": {
    title: "技1A 第7章（確率）",
    problems: [
      { number: 1, level: 1, checkPoint: "2個のサイコロの出た目はどう整理するのがいい？全事象が21通りではダメな理由は？" },
      { number: 3, level: 2, checkPoint: "余事象はどのような時に考える？" },
      { number: 4, level: 2, checkPoint: "和事象の確率を求める際の注意点は？" },
      { number: 5, level: 1, checkPoint: "条件つき確率の定義は？求める公式は？" },
      { number: 6, level: 2, checkPoint: "条件つき確率を整理する上で役立つ方法は？" },
      { number: 9, level: 1, checkPoint: "反復試行の確率とは？求め方は？" },
      { number: 10, level: 2, checkPoint: "試行の終了条件に事象の起こる確率が含まれているとき、注意することは？" },
      { number: 11, level: 2, checkPoint: "サイコロ・コインなどにより点を移動させる問題での考え方は？" },
      { number: 13, level: 2, checkPoint: "大小関係が定められた順列の求め方は？等号・不等号の有無でどう変わる？" },
      { number: 14, level: 2, checkPoint: "サイコロの出た目の最大値・最小値についての確率の求め方は？" },
      { number: 17, level: 2, checkPoint: "玉・くじ・カード型の同時抽出の考え方は？" },
      { number: 18, level: 2, checkPoint: "玉・くじ・カード型の復元抽出の考え方は？" },
      { number: 21, level: 1, checkPoint: "ジャンケンの確率の立式の仕方は？" },
      { number: 22, level: 2, checkPoint: "ジャンケンであいこになる確率はどう求める？ 2通りの求め方は？" },
      { number: 25, level: 1, checkPoint: "期待値の定義は？何を描いて求めるとよい？" },
      { number: 26, level: 2, checkPoint: "期待値を求める際に確率を求めるのが面倒なものに対する工夫は？" },
      { number: 29, level: 1, checkPoint: "確率漸化式を立式する上でのPointは？（詳しくは2学期）" },
      { number: 30, level: 2, checkPoint: "確率漸化式で、n回目に起こる全ての事象についての確率の関係式は？（詳しくは2学期）" },
    ],
  },
  "1a-8": {
    title: "技1A 第8章（整数）",
    problems: [
      { number: 1, level: 1, checkPoint: "2,3,4,5,6,8,9の倍数の判定法は？" },
      { number: 2, level: 1, checkPoint: "1〜nに含まれるpの倍数の個数は？" },
      { number: 3, level: 2, checkPoint: "素数とはどんな数？また、素数条件の扱いの基本ポイントは？" },
      { number: 5, level: 1, checkPoint: "√⚫︎が整数となるための条件は？ また、n/⚫︎が整数になるための条件は？" },
      { number: 6, level: 2, checkPoint: "n! に含まれる素因数pの個数は？" },
      { number: 7, level: 2, checkPoint: "正の約数の個数は？また、総和は？" },
      { number: 9, level: 2, checkPoint: "最大公約数、最小公倍数についての有名な関係3つは？" },
      { number: 11, level: 1, checkPoint: "ユークリッドの互除法を用いた最大公約数の求め方は？" },
      { number: 13, level: 2, checkPoint: "倍数・余りの証明問題において、最も有名な解法とは？" },
      { number: 14, level: 2, checkPoint: "連続n整数の積は何の倍数？この性質はどのような時に用いる？" },
      { number: 15, level: 2, checkPoint: "倍数・余りの証明問題において、特にの形の問題では、どのような方針を考慮する？" },
      { number: 17, level: 1, checkPoint: "合同式とは？ また、その性質とは？" },
      { number: 18, level: 2, checkPoint: "合同式が特に活きるのは、どのような整数の剰余を考える時？" },
      { number: 21, level: 1, checkPoint: "1次不定方程式の解法は？" },
      { number: 22, level: 2, checkPoint: "1次不定方程式で特殊解を見つけにくい時の方法は？" },
      { number: 25, level: 2, checkPoint: "方程式の整数解を求める上での基本方針は？" },
      { number: 26, level: 2, checkPoint: "方程式の整数解を求める上で、積の形を作る以外に考えるべき方針は？" },
      { number: 27, level: 2, checkPoint: "2次方程式の整数解で値をしぼるためによく用いる不等式とは？" },
      { number: 29, level: 1, checkPoint: "n進数を10進数に直す方法は？また、10進数をn進数に直す方法は？" },
      { number: 30, level: 2, checkPoint: "n進法の小数を10進数に直す方法は？また、10進数をn進法の小数に直す方法は？" },
      { number: 31, level: 2, checkPoint: "n進数がm桁である時、どんな式で評価できる？" },
    ],
  },
  "2b-7": {
    title: "技2B 第7章（数列）",
    problems: [
      { number: 1, level: 1, checkPoint: "等差数列・等比数列の数式化はどのようにして行う？" },
      { number: 2, level: 2, checkPoint: "a,b,c の順に等差数列 ときたら…？ また、a,b,c の順に等比数列 ときたら…？" },
      { number: 5, level: 1, checkPoint: "Σ公式、全部言える？ k=1 がスタートでない時はどうする？" },
      { number: 6, level: 2, checkPoint: "初項からnが入るようなものであっても、一般項をきちんとn とk で表し和を求めれる？" },
      { number: 7, level: 2, checkPoint: "部分分数分解により和が求まるものなどは、Σの中身をどのような形にするのが重要？" },
      { number: 9, level: 1, checkPoint: "和から一般項を求める方法は？また、論証上注意すべき点は？" },
      { number: 10, level: 2, checkPoint: "Σ(等差)×(等比) の和の求め方は？" },
      { number: 13, level: 1, checkPoint: "階差数列の一般項の求め方は？また、論証上注意すべき点は？" },
      { number: 15, level: 2, checkPoint: "群数列の解法、説明できる？" },
      { number: 17, level: 1, checkPoint: "格子点の個数の求め方、説明できる？" },
      { number: 18, level: 2, checkPoint: "x＝k で切ると場合分けが面倒な時のコツの1つは？" },
      { number: 21, level: 1, checkPoint: "階差型の漸化式に気づくポイントは？ また、特性方程式からのカタマリ等比形の解法は？" },
      { number: 22, level: 2, checkPoint: "a(n+1) = r・a(n) / (p・a(n) + q^n) 型の解法は？ また、a(n+1) = p^n・a(n) + q^n 型の解法は？" },
      { number: 26, level: 2, checkPoint: "和を含む漸化式の解法のポイントは？" },
      { number: 28, level: 2, checkPoint: "図形列の問題では、どのような図形に着目して何をする？" },
      { number: 29, level: 2, checkPoint: "三項間漸化式の解法の流れを説明できる？" },
      { number: 30, level: 2, checkPoint: "係数対称型(サイクリック)な連立漸化式の解法は？" },
      { number: 33, level: 1, checkPoint: "数学的帰納法のメカニズムを説明できる？" },
      { number: 34, level: 2, checkPoint: "nがらみの数の大小関係を示すには？" },
    ],
  },
};

// 学期ごとの講の一覧。「3学期以降」は高3以降もこのまま追記し続けられるようにするための固定の箱
const terms = [
  {
    id: "term1",
    title: "1学期",
    units: [
      {
        id: "term1-lecture1",
        title: "1学期第1講　技1A 第2章（最大・最小）",
        chapterRef: "1a-2",
        problemNumbers: [1, 2, 3, 4, 5, 7, 9, 10, 11, 13, 15, 17],
        homeworkNumbers: [2, 3, 4, 7, 9, 10, 11, 13, 15, 17],
      },
      {
        id: "term1-lecture2",
        title: "1学期第2講　技1A 第3章（方程式・不等式）",
        chapterRef: "1a-3",
        problemNumbers: [1, 2, 3, 5, 6, 8, 9, 10, 13, 15, 17, 21, 22, 25, 26],
        homeworkNumbers: [2, 3, 6, 8, 10, 13, 15, 17, 22, 25],
      },
      {
        id: "term1-lecture3",
        title: "1学期第3講　技2B 第3章（三角関数）",
        chapterRef: "2b-3",
        problemNumbers: [1, 2, 3, 5, 7, 8, 9, 10, 11, 13, 14, 15, 17, 18, 21, 22, 25, 26, 29, 30, 33, 34],
        homeworkNumbers: [3, 8, 10, 11, 15, 22, 26, 30],
      },
      {
        id: "term1-lecture4",
        title: "1学期第4講　技2B 第4章（指数・対数関数）",
        chapterRef: "2b-4",
        problemNumbers: [1, 2, 3, 5, 6, 9, 10, 11, 13, 14, 15, 17, 18, 21, 22],
        homeworkNumbers: [6, 10, 11, 15, 17, 18, 21, 22],
      },
      {
        id: "term1-lecture5",
        title: "1学期第5講　技2B 第5章（微分法）",
        chapterRef: "2b-5",
        problemNumbers: [1, 2, 3, 5, 6, 7, 9, 10, 11, 13, 14, 17, 18, 19, 21, 25, 26],
        homeworkNumbers: [6, 7, 10, 11, 14, 18, 19, 21, 25, 26],
      },
      {
        id: "term1-lecture6",
        title: "1学期第6講　技2B 第6章（積分法）",
        chapterRef: "2b-6",
        problemNumbers: [1, 2, 5, 6, 9, 10, 11, 13, 14, 17, 18],
        homeworkNumbers: [2, 5, 6, 10, 17, 18],
      },
      {
        id: "term1-lecture7",
        title: "1学期第7講　技1A 第5章（三角比・図形）",
        chapterRef: "1a-5",
        problemNumbers: [1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 13, 14, 15, 17, 18, 21, 22, 25, 26],
        homeworkNumbers: [1, 2, 3, 5, 10, 11, 15, 18, 26],
      },
      {
        id: "term1-lecture8",
        title: "1学期第8講　技2B 第2章（図形と式①）",
        chapterRef: "2b-2",
        problemNumbers: [1, 2, 3, 5, 7, 9, 10, 11, 13, 14, 15, 17, 18, 21],
        homeworkNumbers: [5, 7, 10, 11, 13, 17, 18, 21],
      },
      {
        id: "term1-lecture9",
        title: "1学期第9講　技2B 第2章（図形と式②）",
        chapterRef: "2b-2",
        problemNumbers: [25, 26, 27, 29, 30, 33, 34, 37, 38, 41, 42],
        homeworkNumbers: [25, 26, 27, 29, 30, 33, 38, 41, 42],
      },
      {
        id: "term1-lecture10",
        title: "1学期第10講　技2B 第9章（平面ベクトル）",
        chapterRef: "2b-9",
        problemNumbers: [1, 3, 4, 5, 6, 9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 21, 22, 25, 29],
        homeworkNumbers: [1, 4, 6, 10, 11, 12, 15, 19, 21, 22, 25],
      },
      {
        id: "term1-lecture11",
        title: "1学期第11講　技2B 第9章（空間ベクトル）",
        chapterRef: "2b-9",
        problemNumbers: [33, 34, 37, 38, 39, 41, 42, 43, 45, 46, 49, 50, 53, 54, 57, 58],
        homeworkNumbers: [37, 38, 39, 43, 46, 50, 53, 54, 57, 58],
      },
      {
        id: "term1-lecture12",
        title: "1学期第12講　技1A 第6章（場合の数）",
        chapterRef: "1a-6",
        problemNumbers: [1, 2, 5, 6, 7, 8, 9, 11, 13, 14, 15, 17, 18, 19, 21, 22, 23, 25, 27, 29, 30, 32, 33, 34, 37],
        homeworkNumbers: [2, 9, 11, 14, 15, 18, 19, 22, 23, 25, 27, 29, 32],
      },
      {
        id: "term1-lecture13",
        title: "1学期第13講　技1A 第7章（確率）",
        chapterRef: "1a-7",
        problemNumbers: [1, 3, 4, 5, 6, 9, 10, 11, 13, 14, 17, 18, 21, 22, 25, 26, 29, 30],
        homeworkNumbers: [3, 6, 10, 11, 13, 14, 17, 18, 22, 25, 26],
      },
      {
        id: "term1-lecture14",
        title: "1学期第14講　技1A 第8章（整数①）",
        chapterRef: "1a-8",
        problemNumbers: [1, 2, 3, 5, 6, 7, 9, 11, 13, 14, 15, 17, 18],
        homeworkNumbers: [1, 2, 5, 6, 7, 9, 11, 13, 14, 17, 18],
      },
      {
        id: "term1-lecture15",
        title: "1学期第15講　技1A 第8章（整数②）",
        chapterRef: "1a-8",
        problemNumbers: [21, 22, 25, 26, 27, 29, 30, 31],
        homeworkNumbers: [21, 22, 25, 26, 27, 29, 30, 31],
      },
      {
        id: "term1-lecture17",
        title: "1学期第17講　技2B 第7章（数列①）",
        chapterRef: "2b-7",
        problemNumbers: [1, 2, 5, 6, 7, 9, 10, 13, 15, 17, 18],
        homeworkNumbers: [],
      },
      {
        id: "term1-lecture18",
        title: "1学期第18講　技2B 第7章（数列②）",
        chapterRef: "2b-7",
        problemNumbers: [21, 22, 26, 28, 29, 30, 33, 34],
        homeworkNumbers: [],
      },
    ],
  },
  {
    id: "term2",
    title: "2学期",
    units: [
      // 2学期のデータが届き次第、ここに追加する
    ],
  },
  {
    id: "term3",
    title: "3学期以降",
    units: [
      // 3学期以降（高3含む）のデータはすべてここに追加していく
    ],
  },
];
